// XStringDataBase.h: interface for the _XStringDataBase class.
//
//////////////////////////////////////////////////////////////////////

#ifndef _XSTRINGDATABASE_H_
#define _XSTRINGDATABASE_H_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include <vector>
#include <map>
#include <list>

#define _XGETINTERFACETEXT( strid )  g_StringDataBase.GetTextString( _XSTRINGDB_SN_EODSTRING_XSR, strid )
#define _XGETINTERFACETEXTORDER( strid )  g_StringDataBase.GetTextOrder( _XSTRINGDB_SN_EODSTRING_XSR, strid )
extern  TCHAR	g_NoneString[];

typedef enum _XSTRINGDB_SECTIONDEFINE
{
	_XSTRINGDB_SN_MOBMODEL_XMS				= 0,
	_XSTRINGDB_SN_DUELFIGHTMONEYREF_TXT,
	_XSTRINGDB_SN_DUELRANKREF_TXT,

	_XSTRINGDB_SN_ZONELIST_INI_SHORT,
	_XSTRINGDB_SN_ZONELIST_INI_LONG,
	_XSTRINGDB_SN_ZONELIST_INI_TITLE,

	_XSTRINGDB_SN_BUFFNPCREF_TXT_NAME,
	_XSTRINGDB_SN_BUFFNPCREF_TXT_INFO,

	_XSTRINGDB_SN_CHARACTERCONDITION_XMS_NAME,
	_XSTRINGDB_SN_CHARACTERCONDITION_XMS_CONCEPT,

	_XSTRINGDB_SN_CHARACTERSTATE_XMS_NAME,
	_XSTRINGDB_SN_CHARACTERSTATE_XMS_INFO,

	_XSTRINGDB_SN_MASTERYSKILLCONCEPT_XMS,

	_XSTRINGDB_SN_MASTERY_TABLE_XMS_NAME,

	_XSTRINGDB_SN_MASTERY_TABLE_BMS_NAME,
	_XSTRINGDB_SN_MASTERY_TABLE_BMS_CONTEXT,

	_XSTRINGDB_SN_SKILLCONCEPT_XMS_CLAN,
	_XSTRINGDB_SN_SKILLCONCEPT_XMS_STYPETITLE,
	_XSTRINGDB_SN_SKILLCONCEPT_XMS_STYPECONCEPT,
	_XSTRINGDB_SN_SKILLCONCEPT_XMS_CONCEPT,

	_XSTRINGDB_SN_SKILL_TABLE_XLS_NAME,
	_XSTRINGDB_SN_SKILL_TABLE_XLS_CONCEPT,

	_XSTRINGDB_SN_NICNAMEREF_TXT_TITLE,
	_XSTRINGDB_SN_NICNAMEREF_TXT_INFO,
	_XSTRINGDB_SN_NICNAMEREF_TXT_DETAILINFO,

	_XSTRINGDB_SN_EODSTRING_XSR,

	_XSTRINGDB_SN_ITEMTABLE_NICKNAME,
	_XSTRINGDB_SN_ITEMTABLE_ADDTO,
	_XSTRINGDB_SN_ITEMTABLE_SEED_WEAPON,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_WEAPON,
	_XSTRINGDB_SN_ITEMTABLE_SEED_CLOTHES,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_CLOTHES,
	_XSTRINGDB_SN_ITEMTABLE_SEED_BOOK,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_BOOK,
	_XSTRINGDB_SN_ITEMTABLE_SEED_POTION,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_POTION,
	_XSTRINGDB_SN_ITEMTABLE_SEED_CONSUMING,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_COMSUMING,
	_XSTRINGDB_SN_ITEMTABLE_SEED_ELIXIR,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_ELIXIR,
	_XSTRINGDB_SN_ITEMTABLE_SEED_QUEST,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_QUEST,
	_XSTRINGDB_SN_ITEMTABLE_SEED_ACCESSORY,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_ACCESSORY,
	_XSTRINGDB_SN_ITEMTABLE_SEED_RESOURCE,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_RESOURCE,
	_XSTRINGDB_SN_ITEMTABLE_SEED_LIFE,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_LIFE,
	_XSTRINGDB_SN_ITEMTABLE_SEED_SOCKET,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_SOCKET,
	_XSTRINGDB_SN_ITEMTABLE_SEED_BOX,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_BOX,
	_XSTRINGDB_SN_ITEMTABLE_SEED_BOXKEY,
	_XSTRINGDB_SN_ITEMTABLE_SEED_INFO_BOXKEY,
	_XSTRINGDB_SN_ITEMTABLE_SOCKETSKILLINFO1,
	_XSTRINGDB_SN_ITEMTABLE_SOCKETSKILLINFO2,
	_XSTRINGDB_SN_ITEMTABLE_SOCKETSKILLINFO3,
	_XSTRINGDB_SN_ITEMTABLE_SOCKETSKILLINFO4,

	_XSTRINGDB_SN_NPCDIALOG,
	_XSTRINGDB_SN_QUESTSCRIPTTEXT,

	_XSTRINGDB_SN_AREATITLE,
	_XSTRINGDB_SN_FUNCTIONALOBJECT,

//#ifdef _XDEF_EXPANDSTRINGDBCATEGORY_20070321
	_XSTRINGDB_SN_CACHITEMNAME,
	_XSTRINGDB_SN_CACHITEMDESCRIPTION,
//#endif

	_XSTRINGDB_SN_ROLLNAME_TABLE_XMS,

};

#define _XDEF_XSTRINGDBHEADER			0xFFCF
#define _XDEF_XSTRINGDBSEPARATEDVERSION	0xFF01

#ifdef _XDEF_NEWSTRINGDBFORMAT
	#define _XDEF_XSTRINGDBVERSION			0x0002
	#define _XDEF_MAXLANGUAGECOUNT			8
#else
	#define _XDEF_XSTRINGDBVERSION			0x0001
	#define _XDEF_MAXLANGUAGECOUNT			5
#endif

struct _XTEXTSTRING_INFO
{
	int			iResourceIndex;
	LPTSTR		strTextString;
	int			iParameterOrder;

#ifdef _XJAPANESE
	LPTSTR		strHiraganaTextString;
#endif

	_XTEXTSTRING_INFO()
	{
		strTextString = NULL;
#ifdef _XJAPANESE
		strHiraganaTextString = NULL;
#endif
	}
	~_XTEXTSTRING_INFO()
	{
		SAFE_DELETE_ARRAY( strTextString );
#ifdef _XJAPANESE
		SAFE_DELETE_ARRAY( strHiraganaTextString );
#endif
	}
};

typedef std::vector<_XTEXTSTRING_INFO*>							svdef_XTEXTSTRING_INFO;
typedef std::map<int, _XTEXTSTRING_INFO*>						smdef_XTEXTSTRING_INFOMAP;

typedef struct _XSTRINGSECTIONINFO
{
	int								m_stringcnt;
	TCHAR							m_sectioname[64];
	
	svdef_XTEXTSTRING_INFO			m_StringVector;
	smdef_XTEXTSTRING_INFOMAP		m_StringMap;

	~_XSTRINGSECTIONINFO();	
	
} XSTRINGSECTIONINFO;

typedef struct _XSTRINGSECTIONREADINFO
{
	int		stringcnt;
	TCHAR	sectioname[64];
} XSTRINGSECTIONREADINFO;


typedef struct _XLOCALIZEDATAINFO
{
	int		stringuid;
	int		resourceid;	
	TCHAR	KoreanString[1024];
	int		KoreanOrder;
	TCHAR	VietnameseString[1024];
	int		VietnameseOrder;
	TCHAR	TaiwaneseString[1024];
	int		TaiwaneseOrder;
	TCHAR	EnglishString[1024];
	int		EnglishOrder;
	TCHAR	ChineseString[1024];
	int		ChineseOrder;
} XLOCALIZEDATAINFO;


class _XStringDataBase  
{
public:
	int								m_TotalSectionCount;
	_XSTRINGSECTIONINFO*			m_pSectionInfo;		

public:
	_XStringDataBase();
	virtual ~_XStringDataBase();

	BOOL				Load( LPCTSTR filename, int languageindex  );
	void				Release( void );

	LPTSTR				GetTextString( _XSTRINGDB_SECTIONDEFINE sectionindex, int resourceid );
#ifdef _XJAPANESE
	LPTSTR				GetSubTextString( _XSTRINGDB_SECTIONDEFINE sectionindex, int resourceid );
#endif
	int					GetTextOrder(  _XSTRINGDB_SECTIONDEFINE sectionindex, int resourceid );
	_XTEXTSTRING_INFO*	GetTextInfo(   _XSTRINGDB_SECTIONDEFINE sectionindex, int resourceid );

	LPTSTR				CompositeString( _XSTRINGDB_SECTIONDEFINE sectionindex, int resourceid, 
										 LPVOID	param1 = NULL, LPVOID param2 = NULL, LPVOID	param3 = NULL, LPVOID param4 = NULL,
										 LPVOID	param5 = NULL, LPVOID param6 = NULL, LPVOID	param7 = NULL, LPVOID param8 = NULL );

	LPTSTR				CompositeString( LPTSTR formatstring, int wordorder,
										 LPVOID	param1 = NULL, LPVOID param2 = NULL, LPVOID	param3 = NULL, LPVOID param4 = NULL,
										 LPVOID	param5 = NULL, LPVOID param6 = NULL, LPVOID	param7 = NULL, LPVOID param8 = NULL );
};

extern _XStringDataBase		g_StringDataBase;

#endif // !defined(_XSTRINGDATABASE_H_)
