#ifndef _XPROC_PROCESSDEFINE
#define _XPROC_PROCESSDEFINE

#include <windows.h>

#define _XPROCDEF_BASEID						WM_USER + 500

#define _XPROCDEF_IDEDITENTER					_XPROCDEF_BASEID + 1
#define _XPROCDEF_PWEDITENTER					_XPROCDEF_BASEID + 2
#define _XPROCDEF_CONNECTEDSERVER				_XPROCDEF_BASEID + 3

//#define _XPROCDEF_

#define _XDEF_WTITLE_LOGIN						10046 //_T("Login")
#define _XDEF_LS_LOGINBUTTON					100
#define _XDEF_LS_EXITBUTTON						101
#define _XDEF_LS_EXITPROGRAM					102
#define _XDEF_LS_LOGINFAILED					103
#define _XDEF_LS_CANCELLOGINSERVER				104
#define _XDEF_LS_DOCONNECTGAMESERVER			108

#define _XDEF_WTITLE_SELECTCHARACTER			10047 //_T("SelectCharacter")
#define _XDEF_CS_CONNECTBUTTON					200
#define _XDEF_CS_CREATEBUTTON					201
#define _XDEF_CS_DELETEBUTTON					202
#define _XDEF_CS_CANCELBUTTON					203
#define _XDEF_CS_DELETECHARACTER				204
#define _XDEF_CS_TYPEPASSWORD					205
#define _XDEF_CS_REQUESTDELETECHARACTER			206
#define _XDEF_CS_CHARACTER01BUTTON				207
#define _XDEF_CS_CHARACTER02BUTTON				208
#define _XDEF_CS_CHARACTER03BUTTON				209

#define _XDEF_WTITLE_CREATECHARACTER			10048 //_T("CreateCharacter")
#define _XDEF_CC_CREATEBUTTON					300
#define _XDEF_CC_CANCELBUTTON					301
#define _XDEF_CC_MANBUTTON						302
#define _XDEF_CC_WOMENBUTTON					303
#define _XDEF_CC_ADDBUTON1						304
#define _XDEF_CC_ADDBUTON2						305
#define _XDEF_CC_ADDBUTON3						306
#define _XDEF_CC_ADDBUTON4						307
#define _XDEF_CC_ADDBUTON5						308
#define _XDEF_CC_SUBBUTON1						309
#define _XDEF_CC_SUBBUTON2						310
#define _XDEF_CC_SUBBUTON3						311
#define _XDEF_CC_SUBBUTON4						312
#define _XDEF_CC_SUBBUTON5						313
#define _XDEF_CC_CREATECHARACTER				320
#define _XDEF_CC_REQUESTCHARACTERLIST			321
#define _XDEF_CC_FACELEFTBUTTON					322
#define _XDEF_CC_FACERIGHTBUTTON				323
#define _XDEF_CC_HAIRLEFTBUTTON					324
#define _XDEF_CC_HAIRRIGHTBUTTON				325
#define _XDEF_CC_CLOTHLEFTBUTTON				326
#define _XDEF_CC_CLOTHRIGHTBUTTON				327
#define _XDEF_CC_ZOOM_SLIDER					328
#define _XDEF_CC_ZOOM_LEFTBUTTON				329
#define _XDEF_CC_ZOOM_RIGHTBUTTON				330
#define _XDEF_CC_ROTATE_SLIDER					331
#define _XDEF_CC_ROTATE_LEFTBUTTON				332
#define _XDEF_CC_ROTATE_RIGHTBUTTON				333

// Create Character Parameter -----------------------------------
#define _XDEF_DEFALTPARAMETER_1					8
#define _XDEF_DEFALTPARAMETER_2					8
#define _XDEF_DEFALTPARAMETER_3					8
#define _XDEF_DEFALTPARAMETER_4					8
#define _XDEF_DEFALTPARAMETER_5					8

// Main game process

#define _XDEF_MG_WARPINGNEXTZONE				350
#define _XDEF_MG_CANCELWARPINGNEXTZONE			351


#define _XDEF_WTITLE_FSWINDOW				    10000 //_T("FSWindow")

#define _XDEF_WTITLE_CHARACTERINFO				10001 //_T("CharInfo")
#define	_XDEF_CI_CLOSEBUTTON					705
#define	_XDEF_CI_MODIFYBUTTON1					706
#define	_XDEF_CI_MODIFYBUTTON2					707
#define	_XDEF_CI_MODIFYBUTTON3					708
#define	_XDEF_CI_MODIFYBUTTON4					709
#define	_XDEF_CI_MODIFYBUTTON5					710

#define _XDEF_WTITLE_QUICKSLOT					10002 //_T("QuickSlot")
#define _XDEF_QS_PREVBUTTON						730
#define _XDEF_QS_NEXTBUTTON						731
#define _XDEF_QS_LEVELDOWNBUTTON				732
#define _XDEF_QS_LEVELUPBUTTON					733
#define _XDEF_QS_TYPECHANGEBUTTON				734
#define _XDEF_QS_CLOSEBUTTON				    735
#define _XDEF_QS_LEVELSLIDER					736
#define _XDEF_QS_SHORTCUT1BUTTON				737
#define _XDEF_QS_SHORTCUT2BUTTON				738
#define _XDEF_QS_SHORTCUT3BUTTON				739
#define _XDEF_QS_SHORTCUT4BUTTON				740
#define _XDEF_QS_SHORTCUT5BUTTON				741
#define _XDEF_QS_SHORTCUT6BUTTON				742
#define _XDEF_QS_SHORTCUT7BUTTON				743
#define _XDEF_QS_SHORTCUT8BUTTON				744
#define _XDEF_QS_SHORTCUT9BUTTON				745

#define _XDEF_WTITLE_CHATTINGWINDOWDEFAULT		10003 //_T("Chatting")
#define _XDEF_CHATDEFAULT_WHISPERMODEBUTTON		755
#define _XDEF_CHATDEFAULT_CHATMODE_ALL			756
#define _XDEF_CHATDEFAULT_CHATMODE_SOCIETY      757
#define _XDEF_CHATDEFAULT_CHATMODE_PARRY        758
#define _XDEF_CHATDEFAULT_CHATMODE_FRIEND		759
#define _XDEF_CHATDEFAULT_FUNCTIONBUTTON		760
#define _XDEF_CHATDEFAULT_UPBUTTON				761
#define _XDEF_CHATDEFAULT_DOWNBUTTON			762
#define _XDEF_CHATDEFAULT_RECENTBUTTON			763
#define _XDEF_CHATDEFAULT_STATUSBUTTON			764
#define _XDEF_CHATDEFAULT_RESIZEBUTTON			765

#define _XDEF_WTITLE_MINIMAPWINDOW				10004 //_T("Minimap")
#define _XDEF_MINIMAP_CLOSEBUTTON				770
#define _XDEF_MINIMAP_ZOOMMAXBUTTON				771
#define _XDEF_MINIMAP_ZOOMINBUTTON				772
#define _XDEF_MINIMAP_ZOOMOUTBUTTON				773
#define _XDEF_MINIMAP_CHECKPOINTBUTTON			774

#define _XDEF_WTITLE_MAXMINIMAPWINDOW			10005 //_T("MaxMinimap")
#define _XDEF_MAXMINIMAP_CLOSEBUTTON			780
#define _XDEF_MAXMINIMAP_NPCVIEWBUTTON			781
#define _XDEF_MAXMINIMAP_PARTYVIEWBUTTON		782
#define _XDEF_MAXMINIMAP_APPLYBUTTON			783

#define _XDEF_WTITLE_SKILL						10006 //_T("Skill")
#define _XDEF_SKILLWINDOW_CLOSE					790
#define _XDEF_SKILLWINDOW_MARTIALTAB			791
#define _XDEF_SKILLWINDOW_MAGICFORMULATAB		792
#define _XDEF_SKILLWINDOW_OCCUPATIONTAB			793
#define _XDEF_SKILLWINDOW_ACTIONTAB				794
#define _XDEF_SKILLWINDOW_LISTBOX				795

#define _XDEF_WTITLE_OPTION						10007 //_T("Option")
#define _XDEF_OPTIONWINDOW_CLOSE				800
#define _XDEF_DLGTAB_SCREEN						801
#define _XDEF_DLGTAB_SOUND						802
#define _XDEF_DLGTAB_COMMUNITY					803
#define _XDEF_DLGTAB_EXIT						804
#define _XDEF_DLGTAB_SYSTEMEND					807
#define _XDEF_OPTION_SCREEN_RESOLUTION			820
#define _XDEF_OPTION_SCREEN_DEPTHBUFFER			821
#define _XDEF_OPTION_SCREEN_GAMMA				822
#define _XDEF_OPTION_SCREEN_TERRAINLOD			823
#define _XDEF_OPTION_SCREEN_SIGHTRANGE			827
#define _XDEF_OPTION_SCREEN_GRASSQUALITY		828
#define _XDEF_OPTION_SCREEN_GRASSANIM			829
#define _XDEF_OPTION_SCREEN_TREEANIM			830
#define _XDEF_OPTION_SCREEN_CHARACTORSHADOW		831
#define _XDEF_OPTION_SCREEN_CLOUDESHADOW		832
#define _XDEF_OPTION_SCREEN_EFFECTQUALITY		833
#define _XDEF_OPTION_SCREEN_REFLECTION			834
#define _XDEF_OPTION_SCREEN_LENSFLARE			835
#define _XDEF_OPTION_SOUND_USEBGM				838
#define _XDEF_OPTION_SOUND_BGMVOLUME			839
#define _XDEF_OPTION_SOUND_USEEFFECTSOUND		840
#define _XDEF_OPTION_SOUND_EFFECTSOUNDVOLUME	841
#define _XDEF_OPTION_COMMUNITY_VIEWTOOLTIP		845
#define _XDEF_OPTIONWINDOW_RENDER_GAMMA			 850
#define _XDEF_OPTIONWINDOW_RENDER_DISTANCE		 851
#define _XDEF_OPTIONWINDOW_RENDER_TERRAINANIM	 852
#define _XDEF_OPTIONWINDOW_RENDER_TERRAINDETAILE 853
#define _XDEF_OPTIONWINDOW_RENDER_RTOBJECTANIM	 854
#define _XDEF_OPTIONWINDOW_RENDER_RTGENERATERATE 855


#define _XDEF_WTITLE_PARTY						10008 //_T("Party")
#define _XDEF_PARTYWINDOW_CLOSE					900
#define _XDEF_PARTYWINDOW_TAB_BANGHOI			901
#define _XDEF_PARTYWINDOW_TAB_SEGA				902
#define _XDEF_PARTYWINDOW_TAB_FRIEND			903
#define _XDEF_PARTYWINDOW_TAB_PARTY				904
#define _XDEF_PARTYWINDOW_MASTERMINI			905
#define _XDEF_PARTYWINDOW_LEAVE					906
#define _XDEF_PARTYWINDOW_USERMINI				907
#define _XDEF_PARTYWINDOW_USERSECESSION			908
#define _XDEF_PARTYWINDOW_USERLEAVE				909
#define _XDEF_PARTYWINDOW_LISTBOX				910
#define _XDEF_PARTYWINDOW_DISSOLUTION			911

#define _XDEF_WTITLE_MINIPARTY_MEMBER1			10009 //_T("MiniParty1")
#define _XDEF_WTITLE_MINIPARTY_MEMBER2			10010 //_T("MiniParty2")
#define _XDEF_WTITLE_MINIPARTY_MEMBER3			10011 //_T("MiniParty3")
#define _XDEF_WTITLE_MINIPARTY_MEMBER4			10012 //_T("MiniParty4")
#define _XDEF_WTITLE_MINIPARTY_MEMBER5			10013 //_T("MiniParty5")
#define _XDEF_WTITLE_MINIPARTY_MEMBER6			10014 //_T("MiniParty6")
#define _XDEF_WTITLE_MINIPARTY_MEMBER7			10015 //_T("MiniParty7")
#define _XDEF_WTITLE_MINIPARTY_MEMBER8			10016 //_T("MiniParty8")
#define _XDEF_WTITLE_MINIPARTY_MEMBER9			10017 //_T("MiniParty9")
/*#define _XDEF_WTITLE_MINIPARTY_MEMBER10			10018 //_T("MiniParty10")// 2004.06.01->oneway48 delete
#define _XDEF_WTITLE_MINIPARTY_MEMBER11			10019 //_T("MiniParty11")
#define _XDEF_WTITLE_MINIPARTY_MEMBER12			10020 //_T("MiniParty12")
#define _XDEF_WTITLE_MINIPARTY_MEMBER13			10021 //_T("MiniParty13")
#define _XDEF_WTITLE_MINIPARTY_MEMBER14			10022 //_T("MiniParty14")
#define _XDEF_WTITLE_MINIPARTY_MEMBER15			10023 //_T("MiniParty15")*/

#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON1		921
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON2		922
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON3		923
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON4		924
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON5		925
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON6		926
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON7		927
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON8		928
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON9		929 /*
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON10		930// 2004.06.01->oneway48 delete
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON11		931
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON12		932
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON13		933
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON14		934
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON15		935*/

#define _XDEF_WTITLE_PCTRADE					10024 //_T("PCTrade")
#define _XDEF_PCTRADEWINDOW_CLOSE				950
#define _XDEF_PCTRADEWINDOW_YES					951
#define _XDEF_PCTRADEWINDOW_NO					952
#define _XDEF_PCTRADEWINDOW_OK					953
#define _XDEF_PCTRADEWINDOW_CANCEL				954
#define _XDEF_PCTRADEWINDOW_TRADEMONEY			955
#define _XDEF_PCTRADEWINDOW_INVENTORYMONEY		956

#define _XDEF_WTITLE_NPCSCRIPT					10025 //_T("NPCScript")
#define _XDEF_NPCSCRIPT_CLOSE					1000
#define _XDEF_NPCSCRIPT_MESSAGELIST				1001
#define _XDEF_NPCSCRIPT_SUBSCRIPT1				1002
#define _XDEF_NPCSCRIPT_SUBSCRIPT2				1003
#define _XDEF_NPCSCRIPT_SUBSCRIPT3				1004
#define _XDEF_NPCSCRIPT_SUBSCRIPT4				1005
#define _XDEF_NPCSCRIPT_SUBSCRIPT5				1006
#define _XDEF_NPCSCRIPT_NEXTSCRIPT				1007
#define _XDEF_NPCSCRIPT_RENEW					1008
#define _XDEF_NPCSCRIPT_QA						1009
#define _XDEF_NPCSCRIPT_SAVEPOINT				1010


#define _XDEF_NPCSCRIPT_MAXLINE					100

#define _XDEF_WTITLE_QUESTWINDOW				10026 //_T("Quest")
#define	_XDEF_QW_CLOSEBUTTON					1100
#define	_XDEF_QW_QUESTCOMPLETETABBUTTON			1101
#define	_XDEF_QW_QUESTPROGRESSTABBUTTON			1102
#define _XDEF_QW_QUESTLISTBOX					1103
#define _XDEF_QW_QUESTDESCLISTBOX				1104
#define _XDEF_QW_QUESTCANCEL_BUTTON				1105
#define _XDEF_QW_QUESTINVENTORY					1106
#define	_XDEF_QW_QUESTTABBUTTON01				1107 // 力锋青
#define	_XDEF_QW_QUESTTABBUTTON02				1108 // 公覆青
#define	_XDEF_QW_QUESTTABBUTTON03				1109 // 蛆按青
#define	_XDEF_QW_QUESTTABBUTTON04				1110 // 扁楷青

#define _XDEF_WTITLE_INVENTORY					10027 //_T("Inventory")
#define	_XDEF_INV_CLOSEBUTTON					1200
#define _XDEF_INV_LISTBUTTON					1201
#define _XDEF_INV_HATBUTTON						1202
#define _XDEF_INV_EARRINGBUTTON					1203
#define _XDEF_INV_NECKLACEBUTTON				1204
#define _XDEF_INV_JACKETBUTTON					1205
#define _XDEF_INV_MANTLEBUTTON					1206
#define _XDEF_INV_RINGBUTTON					1207
#define _XDEF_INV_WEAPONBUTTON					1208
#define _XDEF_INV_FISTBUTTON					1209
#define _XDEF_INV_PANTSBUTTON					1210
#define _XDEF_INV_SUPPORTBUTTON					1211
#define _XDEF_INV_AMMUNITIONBUTTON				1212
#define _XDEF_INV_FOOTWEARBUTTON				1213
#define _XDEF_INV_WEARINGBUTTON					1214
#define _XDEF_INV_THROWBUTTON					1215
#define _XDEF_INV_REMOVEBUTTON					1216
#define _XDEF_INV_BASETAB_POCKET				1220
#define _XDEF_INV_BASETAB_BACKPACK				1221
#define _XDEF_INV_BASETAB_PASS					1222
#define _XDEF_INV_SLOTTAB_1						1223
#define _XDEF_INV_SLOTTAB_2						1224
#define _XDEF_INV_INVENTORYMONEY				1225

#define _XDEF_WTITLE_INVENTOOLTIP				10028 //_T("InvenTooltip")

#define _XDEF_WTITLE_SKILLTOOLTIP				10029 //_T("SkillTooltip")

#define _XDEF_WTITLE_LISTBASE					10030 //_T("Listbase")

#define _XDEF_WTITLE_MODELVIEW					10031 //_T("ModelView")

#define _XDEF_WTITLE_MODELDESC					10032 //_T("ModelDesc")

#define _XDEF_WTITLE_IMEWINDOW					10033 //_T("IMEWindow")

#define _XDEF_WTITLE_NPCTRADE					10034 //_T("NPCTrade")
#define _XDEF_NPCTRADE_CLOSE					1300
#define _XDEF_NPCTRADE_FIRST_WEAPONTAB			1301
#define _XDEF_NPCTRADE_FIRST_CLOTHESTAB			1302
#define _XDEF_NPCTRADE_FIRST_POTIONTAB			1303
#define _XDEF_NPCTRADE_SECOND_SHORTTAB			1304
#define _XDEF_NPCTRADE_SECOND_LONGTAB			1305
#define _XDEF_NPCTRADE_SECOND_BOWTAB			1306
#define _XDEF_NPCTRADE_SECOND_SOFTTAB			1307
#define _XDEF_NPCTRADE_SECOND_HIDDENTAB			1308
#define _XDEF_NPCTRADE_SECOND_MUSICTAB			1309
#define _XDEF_NPCTRADE_LISTBOX					1310
#define _XDEF_NPCTRADE_BUYOK					1311
#define _XDEF_NPCTRADE_BUYNO					1312
#define _XDEF_NPCTRADE_SELLOK					1313
#define _XDEF_NPCTRADE_SELLNO					1314

#define _XDEF_WTITLE_MAINMENUWINDOW				10035 //_T("MainMenu")
#define _XDEF_MAINMENU_BATTLE					1400
#define _XDEF_MAINMENU_CHARACTERINFO			1401
#define _XDEF_MAINMENU_INVENTORY				1402
#define _XDEF_MAINMENU_SKILL					1403
#define _XDEF_MAINMENU_LIFE						1404
#define _XDEF_MAINMENU_QUEST					1405
#define _XDEF_MAINMENU_COMMUNITY				1406
#define _XDEF_MAINMENU_MINIMAP					1407
#define _XDEF_MAINMENU_SYSTEMMENU				1408

#define _XDEF_WTITLE_TRADECONFIRM				10036 //_T("TradeConfirm")
#define _XDEF_TRADECONFIRM_CLOSE				1500
#define _XDEF_TRADECONFIRM_ZERO					1501
#define _XDEF_TRADECONFIRM_ONE					1502
#define _XDEF_TRADECONFIRM_TWO					1503
#define _XDEF_TRADECONFIRM_THREE				1504
#define _XDEF_TRADECONFIRM_FOUR					1505
#define _XDEF_TRADECONFIRM_FIVE					1506
#define _XDEF_TRADECONFIRM_SIX					1507
#define _XDEF_TRADECONFIRM_SEVEN				1508
#define _XDEF_TRADECONFIRM_EIGHT				1509
#define _XDEF_TRADECONFIRM_NINE					1510
#define _XDEF_TRADECONFIRM_BACK					1511
#define _XDEF_TRADECONFIRM_RESET				1512
#define _XDEF_TRADECONFIRM_OK					1513
#define _XDEF_TRADECONFIRM_ALL					1514

#define _XDEF_WTITLE_ITEMDROPCONFIRM			10037 //_T("ItemDropConfirm")
#define _XDEF_ITEMDROPCONFIRM_CLOSE				1550
#define _XDEF_ITEMDROPCONFIRM_ZERO				1551
#define _XDEF_ITEMDROPCONFIRM_ONE				1552
#define _XDEF_ITEMDROPCONFIRM_TWO				1553
#define _XDEF_ITEMDROPCONFIRM_THREE				1554
#define _XDEF_ITEMDROPCONFIRM_FOUR				1555
#define _XDEF_ITEMDROPCONFIRM_FIVE				1556
#define _XDEF_ITEMDROPCONFIRM_SIX				1557
#define _XDEF_ITEMDROPCONFIRM_SEVEN				1558
#define _XDEF_ITEMDROPCONFIRM_EIGHT				1559
#define _XDEF_ITEMDROPCONFIRM_NINE				1560
#define _XDEF_ITEMDROPCONFIRM_BACK				1561
#define _XDEF_ITEMDROPCONFIRM_RESET				1562
#define _XDEF_ITEMDROPCONFIRM_OK				1563
#define _XDEF_ITEMDROPCONFIRM_ALL				1564

#define _XDEF_WTITLE_REQUESTPARTY				10038 //_T("RequestParty")
#define _XDEF_REQUESTPARTY_CLOSE				1600
#define _XDEF_REQUESTPARTY_SENDMESSAGE			1601
#define _XDEF_REQUESTPARTY_REQUESTPARTY			1602
#define _XDEF_REQUESTPARTY_JOINPARTYOK			1603
#define _XDEF_REQUESTPARTY_JOINPARTYNO			1604
#define _XDEF_REQUESTPARTY_REQUESTTRADE			1605
#define _XDEF_REQUESTPARTY_REQUESTFRIEND		1606	
#define _XDEF_REQUESTPARTY_FRIENDOK				1607	
#define _XDEF_REQUESTPARTY_FRIENDNO				1608	

#define _XDEF_WTITLE_MESSENGERWINDOW			10039 //_T("Messenger")
#define _XDEF_MESSENGERWINDOW_MINIMIZEBUTTON	 1700 
#define _XDEF_MESSENGERWINDOW_MAXIMIZEBUTTON	 1701
#define _XDEF_MESSENGERWINDOW_CHANGESTATUSBUTTON 1702
#define _XDEF_MESSENGERWINDOW_MESSENGERBUTTON	 1703
#define _XDEF_MESSENGERWINDOW_EMAILBUTTON		 1704
#define _XDEF_MESSENGERWINDOW_LISTBOX			 1705 
#define _XDEF_MESSENGERWINDOW_ADDGROUPBUTTON	 1706
#define _XDEF_MESSENGERWINDOW_ADDFRIENDBUTTON	 1707
#define _XDEF_MESSENGERWINDOW_EMAILRECEIVEBOX	 1708 // 2004.05.27->oneway48 insert
#define _XDEF_MESSENGERWINDOW_EMAILSENDBOX		 1709 
#define _XDEF_MESSENGERWINDOW_EMAILKEEPBOX		 1710 
#define _XDEF_MESSENGERWINDOW_EMAILCLOSE		 1711 
#define _XDEF_MESSENGERWINDOW_EMAILNEXT			 1712 
#define _XDEF_MESSENGERWINDOW_EMAILPREV			 1713 
#define _XDEF_MESSENGERWINDOW_EMAILRECEIVEREPLY	 1714 
#define _XDEF_MESSENGERWINDOW_EMAILRECEIVEDELETE 1715 
#define _XDEF_MESSENGERWINDOW_EMAILSENDDELETE	 1716 
#define _XDEF_MESSENGERWINDOW_EMAILSENDCANCLE	 1717 
#define _XDEF_MESSENGERWINDOW_EMAILSEND			 1718  
#define _XDEF_MESSENGERWINDOW_EMAILKEEP			 1719 

#define _XDEF_WTITLE_JINSTATUSWINDOW			10040 //_T("Jin")
#define _XDEF_JINSTATUS_LEVELUPBUTTON			10041 //2004.06.24->oneway48 insert
#define _XDEF_JINSTATUS_CONVERGENCEBUTTON		10042

#define _XDEF_WTITLE_MONSTERSTATUSWINDOW		10041 //_T("Monster")

#define _XDEF_WTITLE_ZONENAMEWINDOW				10042 //_T("ZoneName")

#define _XDEF_WTITLE_DEATHBLOWWINDOW			10043 //_T("DeathBlow")
#define _XDEF_DEATHBLOW_LEFTBLOWBUTTON			1900
#define _XDEF_DEATHBLOW_RIGHTBLOWBUTTON			1901

#define _XDEF_WTITLE_TRADETOOLTIP				10044 //_T("TradeItemTooltip")

#define _XDEF_WTITLE_SELECTSERVERFOREST 		10045 //_T("SelectServerForestWindow")

#define _XDEF_WTITLE_ZOOM						10049 //_T("ZoomWindow")
#define _XDEF_WTITLE_ROTATE						10050 //_T("RotateWindow")

#define _XDEF_WTITLE_SELECTSERVER				10051 //_T("SelectServerWindow")
#define _XDEF_SELECTSERVERLISTCTRL				2000

#define _XDEF_GAMECLOSE							2100
#define _XDEF_CANCELGAMECLOSE					2101
#define _XDEF_PROCESSTOPSIGNAL					2102
#define _XDEF_GOTOSELECTCHARACTER				2103
#define _XDEF_GOTOLOGINSERVER					2104

#define _XDEF_WTITLE_XDEBUGWINDOW				10051 //_T("XDebug")
#define _XDEF_XDEBUGINFOMODE_BASE				3000		
#define _XDEF_XDEBUGINFOMODE_SYSTEM				3001
#define _XDEF_XDEBUGINFOMODE_VIDEOINFO			3002
#define _XDEF_XDEBUGINFOMODE_WORLD				3003

#define _XDEF_WTITLE_NOTICEWINDOW				10052 //_T("Notice")
#define _XDEF_NOTICEWINDOW_CLOSEBUTTON			3100

#define _XDEF_WTITLE_CHARGEGAUGE				10053 // _T("Charge Gauge")

#define _XDEF_WTITLE_WAREHOUSE					10054 //_T("Warehouse")
#define _XDEF_WAREHOUSEWINDOW_CLOSE				3300
#define _XDEF_WAREHOUSEWINDOW_SENDADDITEM		3301
#define _XDEF_WAREHOUSEWINDOW_ALLSELECT			3302
#define _XDEF_WAREHOUSEWINDOW_STORAGEMONEY		3303
#define _XDEF_WAREHOUSEWINDOW_INVENTORYMONEY	3304

#define _XDEF_WTITLE_ADDSAVEITEM				10055 //_T("AddSaveItem")
#define _XDEF_ADDSAVEITEMWINDOW_CLOSE			3400
#define _XDEF_ADDSAVEITEMWINDOW_OK				3401// 2004.05.20->oneway48 insert
//#define _XDEF_ADDSAVEITEMWINDOW_LISTBOX			3401
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN1		3402 
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN2		3403
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN3		3404
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN4		3405
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN5		3406
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN6		3407
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN7		3408
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN8		3409
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN9		3410 // insert end

#define _XDEF_WTITLE_MESSENGERTOOLTIPWINDOW					10056 //_T("MessengerTooltip")
#define _XDEF_MESSENGERTOOLTIPWINDOW_CLOSEBUTTON			3500
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEFRIENDBUTTON		3501
#define _XDEF_MESSENGERTOOLTIPWINDOW_ADDGROUPBUTTON			3502
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEGROUPBUTTON		3503
#define _XDEF_MESSENGERTOOLTIPWINDOW_CHANGERGROUPNAMEBUTTON	3504
#define _XDEF_MESSENGERTOOLTIPWINDOW_STATUSLISTBOX			3505
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEGROUPOK			3506
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEGROUPNO			3507
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEFRIENDOK			3508
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEFRIENDNO			3509
#define _XDEF_MESSENGERTOOLTIPWINDOW_CHATFUNCTIONLISTBOX	3510
#define _XDEF_MESSENGERTOOLTIPWINDOW_CHATRECENTLISTBOX		3511

#define _XDEF_WTITLE_NAMEINPUTWINDOW			10057 //_T("NameInput") 
#define _XDEF_NAMEINPUTWINDOW_CLOSE				3600
#define _XDEF_NAMEINPUTWINDOW_OK				3601

#define _XDEF_WTITLE_NPCSKILL						10058 //_T("NPCSkill")
#define _XDEF_NPCSKILLWINDOW_CLOSE					3700
#define _XDEF_NPCSKILLWINDOW_MARTIALTAB				3701
#define _XDEF_NPCSKILLWINDOW_MAGICFORMULATAB		3702
#define _XDEF_NPCSKILLWINDOW_OCCUPATIONTAB			3703
#define _XDEF_NPCSKILLWINDOW_ACTIONTAB				3704
#define _XDEF_NPCSKILLWINDOW_LISTBOX				3705
#define _XDEF_NPCSKILLWINDOW_REQLEARNSKILL			3706

#define _XDEF_WTITLE_NPCSKILLTOOLTIP				10059 //_T("NPCSkillTooltip")

#define _XDEF_WTITLE_REBIRTH						10060 // _T("Rebirth")
#define _XDEF_REBIRTHWINDOW_TOWN					3800
#define _XDEF_REBIRTHWINDOW_FIELD					3801
#define _XDEF_REBIRTHWINDOW_WAIT					3802
#define _XDEF_REBIRTHWINDOW_SAVEPOINT				3803

// 2004.06.17->oneway48 insert
#define _XDEF_WTITLE_REPAIRITEM						10061 // _T("Repair Item")
#define _XDEF_REPAIRITEMWINDOW_ALLBUTTON			3900
#define _XDEF_REPAIRITEMWINDOW_REPAIRBUTTON			3901
#define _XDEF_REPAIRITEMWINDOW_CANCLE				3902
#define _XDEF_REPAIRITEMWINDOW_ALLREPAIRYES			3903
#define _XDEF_REPAIRITEMWINDOW_ALLREPAIRNO			3904
// insert

#define _XDEF_WTITLE_MEDITATION						10062 // _T("Meditation(Minigame))" 2004.06.15->hotblood
#define _XDEF_MEDITATION_YES						4001
#define _XDEF_MEDITATION_NO							4002
#define _XDEF_MEDITATION_START						4003
#define _XDEF_MEDITATION_EXIT						4004
#define _XDEF_MEDITATION_HELP						4005

#define _XDEF_WTITLE_GAUGE							10063 // hotblood

#define _XDEF_WTITLE_HELP							10064 // hotblood

#define _XDEF_WTITLE_TRAININGMEDITATION				10065  // _T("Training Meditation")
#define _XDEF_TRAINING_MEDITATION_START				4100
#define _XDEF_TRAINING_MEDITATION_EXIT				4101
#define _XDEF_TRAINING_MEDITATION_HELP				4102

#define _XDEF_TRAINING_DUMMY_START					4200
#define _XDEF_WTITLE_TRAININGDUMMY					10066	// _T("Training Dummy")
#define _XDEF_TRAINING_HELP_CLOSE					4201
#define _XDEF_TRAINING_CANCEL_OK					4202
#define _XDEF_TRAINING_CANCEL_NO					4203
#define _XDEF_TRAINING_SPELL_START					4204

#define _XDEF_WTITLE_TRAININGSPELL					10067

#define _XDEF_WTITLE_MESSAGEWINDOW					30000 // "Message window"


#define _XDEF_RENDERTEXTURERANGE	3.0f
#define _XDEF_SHADOWOBJECTRANGE		2.0f

#define _XDEF_MESSAGEDIALOGDLGPOS_WIDTH		320
#define _XDEF_MESSAGEDIALOGDLGPOS_HEIGHT	63

#endif //end of _XPROC_PROCESSDEFINE
