#ifndef _XPROC_PROCESSDEFINE
#define _XPROC_PROCESSDEFINE

#include <windows.h>

#define _XPROCDEF_BASEID						WM_USER + 693

#define _XPROCDEF_IDEDITENTER					_XPROCDEF_BASEID + 1
#define _XPROCDEF_PWEDITENTER					_XPROCDEF_BASEID + 2
#define _XPROCDEF_CONNECTEDSERVER				_XPROCDEF_BASEID + 3

//#define _XPROCDEF_

#define _XDEF_WTITLE_LOGIN						10046 //_T("Login")
#define _XDEF_LS_LOGINBUTTON					100
#define _XDEF_LS_EXITBUTTON						101
#define _XDEF_LS_EXITPROGRAM					102
#define _XDEF_LS_LOGINFAILED					103
#define _XDEF_LS_CANCELLOGINSERVER				104
#define _XDEF_LS_SERVERREFRESHBUTTON			105
#define _XDEF_LS_SERVERLISTCLOSEBUTTON			106
#define _XDEF_LS_VIEWSERVERLISTBUTTON			107
#define _XDEF_LS_DOCONNECTGAMESERVER			108
#define _XDEF_LS_TESTSERVERNOTICEWINDOWCLOSEBTN	109
#define _XDEF_LS_SAVELASTLOGINUSER				110
#define _XDEF_LS_DRAWKEYBOARD					111
#define _XDEF_LS_COMPULSORYSTEP1YES				112
#define _XDEF_LS_COMPULSORYSTEP2YES				113
#define _XDEF_LS_COMPULSORYSTEP3YES				114
#define _XDEF_LS_COMPULSORYSTEP4YES				115
#define _XDEF_LS_COMPULSORYSTEP5YES				116

#define _XDEF_WTITLE_SELECTCHARACTER			10047 //_T("SelectCharacter")
#define _XDEF_CS_CONNECTBUTTON					200
#define _XDEF_CS_CREATEBUTTON					201
#define _XDEF_CS_DELETEBUTTON					202
#define _XDEF_CS_CANCELBUTTON					203
#define _XDEF_CS_CANCELDELETEBUTTON				204
#define _XDEF_CS_DELETECHARACTER				205
#define _XDEF_CS_TYPEPASSWORD					206
#define _XDEF_CS_REQUESTDELETECHARACTER			207
#define _XDEF_CS_CHARACTER01BUTTON				208
#define _XDEF_CS_CHARACTER02BUTTON				209
#define _XDEF_CS_CHARACTER03BUTTON				210
#define _XDEF_CS_DELETEAGAINCHARACTER			211

#define _XDEF_WTITLE_CREATECHARACTER			10048 //_T("CreateCharacter")
#define _XDEF_CC_CREATEBUTTON					300
#define _XDEF_CC_CANCELBUTTON					301
#define _XDEF_CC_MANBUTTON						302
#define _XDEF_CC_WOMENBUTTON					303
#define _XDEF_CC_ADDBUTON1						304
#define _XDEF_CC_ADDBUTON2						305
#define _XDEF_CC_ADDBUTON3						306
#define _XDEF_CC_ADDBUTON4						307
#define _XDEF_CC_ADDBUTON5						308
#define _XDEF_CC_SUBBUTON1						309
#define _XDEF_CC_SUBBUTON2						310
#define _XDEF_CC_SUBBUTON3						311
#define _XDEF_CC_SUBBUTON4						312
#define _XDEF_CC_SUBBUTON5						313
#define _XDEF_CC_CREATECHARACTER				320
#define _XDEF_CC_REQUESTCHARACTERLIST			321
#define _XDEF_CC_FACELEFTBUTTON					322
#define _XDEF_CC_FACERIGHTBUTTON				323
#define _XDEF_CC_HAIRLEFTBUTTON					324
#define _XDEF_CC_HAIRRIGHTBUTTON				325
#define _XDEF_CC_CLOTHLEFTBUTTON				326
#define _XDEF_CC_CLOTHRIGHTBUTTON				327
#define _XDEF_CC_ZOOM_SLIDER					328
#define _XDEF_CC_ZOOM_LEFTBUTTON				329
#define _XDEF_CC_ZOOM_RIGHTBUTTON				330
#define _XDEF_CC_ROTATE_SLIDER					331
#define _XDEF_CC_ROTATE_LEFTBUTTON				332
#define _XDEF_CC_ROTATE_RIGHTBUTTON				333
#define _XDEF_CC_AREACHECKBUTTON1				334
#define _XDEF_CC_AREACHECKBUTTON2				335
#define _XDEF_CC_AREACHECKBUTTON3				336
#define _XDEF_CC_AREACHECKBUTTON4				337
#define _XDEF_CC_AREACHECKBUTTON5				338
#define _XDEF_CC_AREACHECKBUTTON6				339
#define _XDEF_CC_AREACHECKBUTTON7				340
#define _XDEF_CC_AREACHECKBUTTON8				341
#define _XDEF_CC_AREACHECKBUTTON9				342
#define _XDEF_CC_EXITBUTTON						343

// Create Character Parameter -----------------------------------
#define _XDEF_DEFALTPARAMETER_1					8
#define _XDEF_DEFALTPARAMETER_2					8
#define _XDEF_DEFALTPARAMETER_3					8
#define _XDEF_DEFALTPARAMETER_4					8
#define _XDEF_DEFALTPARAMETER_5					8

// Main game process

#define _XDEF_MG_WARPINGNEXTZONE				350
#define _XDEF_MG_CANCELWARPINGNEXTZONE			351
#define _XDEF_MG_MOVEPKSERVER_YES				352
#define _XDEF_MG_MOVEPKSERVER_NO				353


#define _XDEF_WTITLE_FSWINDOW				    10000 //_T("FSWindow")

#define _XDEF_WTITLE_CHARACTERINFO				10001 //_T("CharInfo")
#define	_XDEF_CI_CLOSEBUTTON					705
#define	_XDEF_CI_MODIFYBUTTON1					706
#define	_XDEF_CI_MODIFYBUTTON2					707
#define	_XDEF_CI_MODIFYBUTTON3					708
#define	_XDEF_CI_MODIFYBUTTON4					709
#define	_XDEF_CI_MODIFYBUTTON5					710

#define	_XDEF_CI_NICKBUTTON_MARRIAGE			711
#define	_XDEF_CI_NICKBUTTON_MASTERANDPUPIL		712
#define	_XDEF_CI_NICKBUTTON_NICKNAME			713
#define	_XDEF_CI_MATCHBUTTON					714
#define	_XDEF_CI_IVENTORYBUTTON					715
#define	_XDEF_CI_FAVORITESNICKNAMELIST			716
#define	_XDEF_CI_FAVORITESNICKNAMELIST_BTN		717

#define _XDEF_WTITLE_QUICKSLOT					10002 //_T("QuickSlot")
#define _XDEF_QS_PREVBUTTON						730
#define _XDEF_QS_NEXTBUTTON						731
#define _XDEF_QS_LEVELDOWNBUTTON				732
#define _XDEF_QS_LEVELUPBUTTON					733
#define _XDEF_QS_SHORTCUT1BUTTON				734
#define _XDEF_QS_SHORTCUT2BUTTON				735
#define _XDEF_QS_SHORTCUT3BUTTON				736
#define _XDEF_QS_SHORTCUT4BUTTON				737
#define _XDEF_QS_SHORTCUT5BUTTON				738
#define _XDEF_QS_SHORTCUT6BUTTON				739
#define _XDEF_QS_SHORTCUT7BUTTON				740
#define _XDEF_QS_SHORTCUT8BUTTON				741
#define _XDEF_QS_SHORTCUT9BUTTON				742
#define _XDEF_QS_SHORTCUT0BUTTON				743
#define _XDEF_QS_BATTLEMODEBUTTON				744


#define _XDEF_WTITLE_CHATTINGWINDOWDEFAULT		10003 //_T("Chatting")
#define _XDEF_CHATDEFAULT_RECENTBUTTON			754
#define _XDEF_CHATDEFAULT_RESIZEBUTTON			755

#define _XDEF_CHATDEFAULT_WHISPERTARGETBUTTON1	756
#define _XDEF_CHATDEFAULT_WHISPERTARGETBUTTON2	757
#define _XDEF_CHATDEFAULT_WHISPERTARGETBUTTON3	758

#define _XDEF_CHATDEFAULT_DOCKINGSYSTEMMESSAGE  759

#define _XDEF_CHATDEFAULT_FUNCTIONBUTTON			760
#define _XDEF_CHATDEFAULT_FUNCTION_EMOTIONBUTTON	761

#define _XDEF_CHATDEFAULT_FUNCTION_SHOUTBUTTON		762
#define _XDEF_CHATDEFAULT_FUNCTION_CLANBUTTON		763
#define _XDEF_CHATDEFAULT_FUNCTION_SUBCLANBUTTON	764
#define _XDEF_CHATDEFAULT_FUNCTION_PARTYBUTTON		765
#define _XDEF_CHATDEFAULT_FUNCTION_WHISPERBUTTON	766
#define _XDEF_CHATDEFAULT_FUNCTION_ZONEBUTTON		767
#define _XDEF_CHATDEFAULT_FUNCTION_ALLBUTTON		768
#define _XDEF_CHATDEFAULT_EMOTIONLISTBOX			769

#define _XDEF_CHATDEFAULT_RETURNTOTOWN				770
#define _XDEF_CHATDEFAULT_NORMALFILTERMENUBUTTON	771
#define _XDEF_CHATDEFAULT_WHISPERFILTERMENUBUTTON	772
#define _XDEF_CHATDEFAULT_PARTYFILTERMENUBUTTON		773
#define _XDEF_CHATDEFAULT_HEROBANDFILTERMENUBUTTON	774
#define _XDEF_CHATDEFAULT_LOCKFILTERMENUBUTTON		813
#define _XDEF_CHATDEFAULT_CHATBLACKLISTUBUTTON		814
#define _XDEF_CHATDEFAULT_USER_CHATBLACKLISTUBUTTON	815


#define _XDEF_WTITLE_MINIMAPWINDOW				10004 //_T("Minimap")
#define _XDEF_MINIMAP_CLOSEBUTTON				775 
#define _XDEF_MINIMAP_ZOOMMAXBUTTON				776
#define _XDEF_MINIMAP_ZOOMINBUTTON				777
#define _XDEF_MINIMAP_ZOOMOUTBUTTON				778
#define _XDEF_MINIMAP_WORLDMAPBUTTON			779
#define _XDEF_MINIMAP_HELPBOOKBTN				784	// 밑에거 씀
#define _XDEF_MINIMAP_NPCSEARCHBTN				785	// NPC 찾기 기능
#define _XDEF_MINIMAP_BTN_WEBBOARD				799	// 웹게시판 열기 번호가 없어서 799번을 씀.
#define _XDEF_MINIMAP_BTN_PKTRACING				812	// PK범 추적의뢰 열기 번호가 없어서 812번을 씀.

#define _XDEF_WTITLE_MAXMINIMAPWINDOW			10005 //_T("MaxMinimap")
#define _XDEF_MAXMINIMAP_CLOSEBUTTON			780
#define _XDEF_MAXMINIMAP_NPCVIEWBUTTON			781
#define _XDEF_MAXMINIMAP_PARTYVIEWBUTTON		782
#define _XDEF_MAXMINIMAP_APPLYBUTTON			783
#define _XDEF_MAXMINIMAP_ALPHASLIDER			798 // Author : 양희왕 //breif : 투명도 슬라이더

#define _XDEF_WTITLE_SKILL						10006 //_T("Skill")
#define _XDEF_SKILLWINDOW_LEFT					786
#define _XDEF_SKILLWINDOW_RIGHT					787
#define _XDEF_SKILLWINDOW_LISTBOX				788
#define _XDEF_SKILLWINDOW_SKILL_1				789
#define _XDEF_SKILLWINDOW_SKILL_2				790
#define _XDEF_SKILLWINDOW_SKILL_3				791
#define _XDEF_SKILLWINDOW_SKILL_4				792
#define _XDEF_SKILLWINDOW_SKILL_5				793
#define _XDEF_SKILLWINDOW_SKILL_6				794
#define _XDEF_SKILLWINDOW_SKILL_7				795
#define _XDEF_SKILLWINDOW_SKILL_8				796
#define _XDEF_SKILLWINDOW_SKDESCLSTBOX			797
// 웹게시판 열기 번호가 없어서 799번을 씀.

#define _XDEF_WTITLE_OPTION						10007 //_T("Option")
#define _XDEF_OPTIONWINDOW_CLOSE				800
#define _XDEF_OPTIONWINDOW_HELPBUTTON			801

#define _XDEF_DLGTAB_GRAPHIC					802
#define _XDEF_DLGTAB_SOUND						803
#define _XDEF_DLGTAB_GAME						804
#define _XDEF_DLGTAB_COMMUNITY					805
#define _XDEF_DLGTAB_SYSTEMEND					806

#define _XDEF_OPTIONWINDOW_GAMECLOSE			810
#define _XDEF_OPTIONWINDOW_GOTOCHARACTERSELECT	811
// PK범 추적의뢰 열기 번호가 없어서 812번을 씀.
//#define _XDEF_CHATDEFAULT_LOCKFILTERMENUBUTTON		813
//#define _XDEF_CHATDEFAULT_CHATBLACKLISTUBUTTON		814
//#define _XDEF_CHATDEFAULT_USER_CHATBLACKLISTUBUTTON	815

#define _XDEF_OPTION_SCREENWINDOW				820
#define _XDEF_OPTION_SCREEN_RESOLUTION			821
#define _XDEF_OPTION_SCREEN_DEPTHBUFFER			822
#define _XDEF_OPTION_SCREEN_GAMMA				823
#define _XDEF_OPTION_SCREEN_TERRAINLOD			824
#define _XDEF_OPTION_SCREEN_SIGHTRANGE			825
#define _XDEF_OPTION_SCREEN_GRASSQUALITY		826
#define _XDEF_OPTION_SCREEN_GRASSANIM			827
#define _XDEF_OPTION_SCREEN_TREEANIM			828
#define _XDEF_OPTION_SCREEN_CHARACTORSHADOW		829
#define _XDEF_OPTION_SCREEN_USEBLOOMFILTER		830
#define _XDEF_OPTION_SCREEN_ENABLEBLOOMFILTER	831
#define _XDEF_OPTION_SCREEN_EFFECTQUALITY		832
#define _XDEF_OPTION_SCREEN_REFLECTION			833
#define _XDEF_OPTION_SCREEN_LENSFLARE			834

#define _XDEF_OPTION_SOUNDWINDOW				840
#define _XDEF_OPTION_SOUND_USEBGM				841
#define _XDEF_OPTION_SOUND_BGMVOLUME			842
#define _XDEF_OPTION_SOUND_USEEFFECTSOUND		843
#define _XDEF_OPTION_SOUND_EFFECTSOUNDVOLUME	844
#define _XDEF_OPTION_SOUND_USEENVSOUND			845
#define _XDEF_OPTION_SOUND_ENVVOLUMESLIDER		846
#define _XDEF_OPTION_SOUND_USEGUIDESOUND		847

#define _XDEF_OPTION_COMMUNITYWINDOW			850
#define _XDEF_OPTION_COMMUNITYREJECTIONWHISPER  851
#define _XDEF_OPTION_COMMUNITYREJECTFRIEND      852
#define _XDEF_OPTION_COMMUNITYREJECTORGANIZATION 853
#define _XDEF_OPTION_COMMUNITYREJECTPARTY		854
#define _XDEF_OPTION_COMMUNITYEXCHANGE			855
#define _XDEF_OPTION_COMMUNITYTARGETINFO		856
#define _XDEF_OPTION_COMMUNITYCONNECTMESSENGER  857
#define _XDEF_OPTION_COMMUNITYDISABLEZONECHAT	858


#define _XDEF_OPTION_GAMEWINDOW					860
#define _XDEF_OPTION_GAME_GAMEGUIDE				861
#define _XDEF_OPTION_GAME_VIEWUSERTOOLTIP		862
#define _XDEF_OPTION_GAME_HELPSYSTEM			863
#define _XDEF_OPTION_GAME_CAMERAQUATERVIEW		864
#define _XDEF_OPTION_GAME_USEFIRSTPERSONVIEW	865
#define _XDEF_OPTION_GAME_VIEWMONSTERGAUGE		866
#define _XDEF_OPTION_GAME_VIEWBATTLEGAUGE		867
#define _XDEF_OPTION_GAME_VIEWMYTOOLTIP			868
#define _XDEF_OPTION_GAME_VIEWITEMTOOLTIP		869
#define _XDEF_OPTION_GAME_RANKHIDING			870
#define _XDEF_OPTION_GAME_DENYMATCH				871
#define _XDEF_OPTION_GAME_CHATTINGAUTOCLOSE		872
#define _XDEF_OPTION_GAME_KEYTYPE_A				873
#define _XDEF_OPTION_GAME_KEYTYPE_B				874
#define _XDEF_OPTION_GAME_SELECTCLOTHES			875

#define _XDEF_WTITLE_PARTY						10008 //_T("Party")
#define _XDEF_PARTYWINDOW_CLOSE					900
#define _XDEF_PARTYWINDOW_TAB_BANGHOI			901
#define _XDEF_PARTYWINDOW_TAB_SEGA				902
#define _XDEF_PARTYWINDOW_TAB_FRIEND			903
#define _XDEF_PARTYWINDOW_TAB_PARTY				904
#define _XDEF_PARTYWINDOW_MASTERMINI			905
#define _XDEF_PARTYWINDOW_LEAVE					906
#define _XDEF_PARTYWINDOW_USERMINI				907
#define _XDEF_PARTYWINDOW_USERSECESSION			908
#define _XDEF_PARTYWINDOW_USERLEAVE				909
#define _XDEF_PARTYWINDOW_LISTBOX				910
#define _XDEF_PARTYWINDOW_DISSOLUTION			911

#define _XDEF_WTITLE_MINIPARTY_MEMBER1			10009 //_T("MiniParty1") partymaster
#define _XDEF_WTITLE_MINIPARTY_MEMBER2			10010 //_T("MiniParty2") partymember
#define _XDEF_WTITLE_MINIPARTY_MEMBER3			10011 //_T("MiniParty3")
#define _XDEF_WTITLE_MINIPARTY_MEMBER4			10012 //_T("MiniParty4")
#define _XDEF_WTITLE_MINIPARTY_MEMBER5			10013 //_T("MiniParty5")
#define _XDEF_WTITLE_MINIPARTY_MEMBER6			10014 //_T("MiniParty6")
#define _XDEF_WTITLE_MINIPARTY_MEMBER7			10015 //_T("MiniParty7")
#define _XDEF_WTITLE_MINIPARTY_MEMBER8			10016 //_T("MiniParty8")
#define _XDEF_WTITLE_MINIPARTY_MEMBER9			10017 //_T("MiniParty9")

#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON1		921// partymaster
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON2		922
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON3		923
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON4		924
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON5		925
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON6		926
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON7		927
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON8		928
#define _XDEF_MINIPARTYWINDOW_CLOSEBUTTON9		929 
#define _XDEF_MINIPARTYWINDOW_MINIMIZEBUTTON	930// partymaster
#define _XDEF_MINIPARTYWINDOW_MAXIMIZEBUTTON	931// partymaster
#define _XDEF_MINIPARTYWINDOW_EXPSHARINGBUTTON	932// partymaster
#define _XDEF_MINIPARTYWINDOW_ITEMSHARINGBUTTON	933// partymaster
#define _XDEF_MINIPARTYWINDOW_ENTRUSTBUTTON1	934
#define _XDEF_MINIPARTYWINDOW_ENTRUSTBUTTON2	935
#define _XDEF_MINIPARTYWINDOW_ENTRUSTBUTTON3	936
#define _XDEF_MINIPARTYWINDOW_ENTRUSTBUTTON4	937
#define _XDEF_MINIPARTYWINDOW_ENTRUSTBUTTON5	938
#define _XDEF_MINIPARTYWINDOW_ENTRUSTBUTTON6	939
#define _XDEF_MINIPARTYWINDOW_ENTRUSTBUTTON7	940
#define _XDEF_MINIPARTYWINDOW_ENTRUSTBUTTON8	941 
#define _XDEF_MINIPARTYWINDOW_YES_PARTYDISSOLUTION 		942
#define _XDEF_MINIPARTYWINDOW_YES_PARTYMEMBERLEAVE		943
#define _XDEF_MINIPARTYWINDOW_YES_PARTYLEAVE			944
#define _XDEF_MINIPARTYWINDOW_YES_PARTYMASTERENTRUST	945
#define _XDEF_MINIPARTYWINDOW_EXPSHAERINGLISTBOX		946
#define _XDEF_MINIPARTYWINDOW_ITEMSHAERINGLISTBOX		947
#define _XDEF_MINIPARTYWINDOW_NO_PARTYREQUEST			948



#define _XDEF_WTITLE_PCTRADE					10024 //_T("PCTrade")
#define _XDEF_PCTRADEWINDOW_CLOSE				950
#define _XDEF_PCTRADEWINDOW_YES					951
#define _XDEF_PCTRADEWINDOW_NO					952
#define _XDEF_PCTRADEWINDOW_OK					953
#define _XDEF_PCTRADEWINDOW_CANCEL				954
#define _XDEF_PCTRADEWINDOW_HELP				955
#define _XDEF_PCTRADEWINDOW_MONEY				956

// skill window button 추가 - 2006.05.12
//#define _XDEF_WTITLE_SKILL						10006 //_T("Skill")
#define _XDEF_SKILLWINDOW_SKILLSORT_1			980
#define _XDEF_SKILLWINDOW_SKILLSORT_2			981
#define _XDEF_SKILLWINDOW_SKILLSORT_3			982
#define _XDEF_SKILLWINDOW_SKILLSORT_4			983
#define _XDEF_SKILLWINDOW_SKILLSORT_5			984
#define _XDEF_SKILLWINDOW_SKILLSORT_6			985
#define _XDEF_SKILLWINDOW_SKILLSORT_7			986
#define _XDEF_SKILLWINDOW_SKILLSORT_8			987

#define _XDEF_WTITLE_NPCSCRIPT					10025 //_T("NPCScript")
#define _XDEF_NPCSCRIPT_CLOSE					1000
#define _XDEF_NPCSCRIPT_MESSAGELIST				1001
#define _XDEF_NPCSCRIPT_SUBSCRIPT1				1002
#define _XDEF_NPCSCRIPT_SUBSCRIPT2				1003
#define _XDEF_NPCSCRIPT_SUBSCRIPT3				1004
#define _XDEF_NPCSCRIPT_SUBSCRIPT4				1005
#define _XDEF_NPCSCRIPT_SUBSCRIPT5				1006
#define _XDEF_NPCSCRIPT_NEXTSCRIPT				1007
#define _XDEF_NPCSCRIPT_RENEW					1008
#define _XDEF_NPCSCRIPT_QA						1009
#define _XDEF_NPCSCRIPT_SAVEPOINT				1010
#define _XDEF_NPCSCRIPT_QUESTOK					1011
#define _XDEF_NPCSCRIPT_LISTBOXQUESTREWARD		1012
#define _XDEF_NPCSCRIPT_LISTBOXSELECTION		1013
#define _XDEF_NPCSCRIPT_BACKTONPCMODE			1014
#define _XDEF_NPCSCRIPT_HEALOK					1015
#define _XDEF_NPCSCRIPT_MINISTOPOK				1016
#define _XDEF_NPCSCRIPT_NPCDIALOGNEXTPAGE		1017
#define _XDEF_NPCSCRIPT_EVENTREWARDYES			1018
#define _XDEF_NPCSCRIPT_EVENTREWARDNO			1019
#define _XDEF_NPCSCRIPT_LISTBOXHAVEQUESTLIST	1020
#define _XDEF_NPCSCRIPT_MASTERNICKNAMEYES		1021 //Author : 양희왕 //breif : 사호 신청 
#define _XDEF_NPCSCRIPT_MASTERNICKNAMENO		1022 //Author : 양희왕 //breif : 사호 취소

#define _XDEF_NPCSCRIPT_MAXLINE					100

#define _XDEF_WTITLE_QUESTWINDOW				10026 //_T("Quest")
#define	_XDEF_QW_CLOSEBUTTON					1100
#define	_XDEF_QW_QUESTCOMPLETETABBUTTON			1101
#define	_XDEF_QW_QUESTPROGRESSTABBUTTON			1102
#define _XDEF_QW_QUESTLISTBOX					1103
#define _XDEF_QW_QUESTDESCLISTBOX				1104
#define _XDEF_QW_QUESTCANCEL_BUTTON				1105
#define _XDEF_QW_QUESTINVENTORY					1106
#define	_XDEF_QW_QUESTTABBUTTON01				1107 // 제룡행
#define	_XDEF_QW_QUESTTABBUTTON02				1108 // 무림행
#define	_XDEF_QW_QUESTTABBUTTON03				1109 // 협객행
#define	_XDEF_QW_QUESTTABBUTTON04				1110 // 기연행
#define	_XDEF_QW_QUESTTABBUTTON05				1111 // 무림소사
#define _XDEF_QW_QUESTREWARDLISTBOX				1112
#define _XDEF_QW_QUESTCANCEL_OK					1113 //퀘스트 포기 확인버튼 
#define _XDEF_QW_QUESTCANCEL_CANCLE				1114 //퀘스트 포기 취소버튼 
#define _XDEF_QW_QUESTTAB_PREV					1115 //퀘스트 이전탭
#define _XDEF_QW_QUESTTAB_NEXT					1116 //퀘스트 다음탭

#define _XDEF_WTITLE_INVENTORY					10027 //_T("Inventory")
#define	_XDEF_INV_CLOSEBUTTON					1200
#define _XDEF_INV_LISTBUTTON					1201
#define _XDEF_INV_HATBUTTON						1202
#define _XDEF_INV_EARRINGBUTTON					1203
#define _XDEF_INV_NECKLACEBUTTON				1204
#define _XDEF_INV_JACKETBUTTON					1205
#define _XDEF_INV_MANTLEBUTTON					1206
#define _XDEF_INV_RINGBUTTON					1207
#define _XDEF_INV_WEAPONBUTTON					1208
#define _XDEF_INV_FISTBUTTON					1209
#define _XDEF_INV_PANTSBUTTON					1210
#define _XDEF_INV_SUPPORTBUTTON					1211
#define _XDEF_INV_AMMUNITIONBUTTON				1212
#define _XDEF_INV_FOOTWEARBUTTON				1213
#define _XDEF_INV_WEARINGBUTTON					1214
#define _XDEF_INV_THROWBUTTON					1215
#define _XDEF_INV_REMOVEBUTTON					1216
#define _XDEF_INV_BASETAB_POCKET				1220
#define _XDEF_INV_BASETAB_BACKPACK				1221
#define _XDEF_INV_BASETAB_BACKPACK2				1222
#define _XDEF_INV_CHARINFO						1223
#define _XDEF_INV_INVENTORYMONEY				1224
#define	_XDEF_INV_HELPBUTTON					1225
#define	_XDEF_INV_USEELIXIRYES					1226
#define	_XDEF_INV_USEELIXIRNO					1227
#define	_XDEF_INV_USEBOOKYES					1228
#define	_XDEF_INV_USEBOOKNO						1229
#define	_XDEF_INV_CASHITEMBUTTON				1230
#define	_XDEF_INV_WASTBASKET_CANCLE				1231
#define	_XDEF_INV_WASTBASKET_CHECKPASSWOAD		1232
#define	_XDEF_INV_WASTBASKET_CASHITEM			1233
#define	_XDEF_INV_WASTBASKET_NORMALITEM			1234
#define _XDEF_INV_BASETAB_CASHBACKPACK1			1235
#define _XDEF_INV_BASETAB_CASHBACKPACK2			1236

#define _XDEF_WTITLE_LISTBASE					10030 //_T("Listbase")

#define _XDEF_WTITLE_MODELVIEW					10031 //_T("ModelView")

#define _XDEF_WTITLE_MODELDESC					10032 //_T("ModelDesc")

#define _XDEF_WTITLE_IMEWINDOW					10033 //_T("IMEWindow")
#define _XDEF_IMECADIDATELISTBOX				1250

#define _XDEF_WTITLE_NPCTRADE					10034 //_T("NPCTrade")
#define _XDEF_NPCTRADE_CLOSE					1300
#define _XDEF_NPCTRADE_FIRST_WEAPONTAB			1301
#define _XDEF_NPCTRADE_FIRST_CLOTHESTAB			1302
#define _XDEF_NPCTRADE_FIRST_POTIONTAB			1303
#define _XDEF_NPCTRADE_SECOND_SHORTTAB			1304
#define _XDEF_NPCTRADE_SECOND_LONGTAB			1305
#define _XDEF_NPCTRADE_SECOND_BOWTAB			1306
#define _XDEF_NPCTRADE_SECOND_SOFTTAB			1307
#define _XDEF_NPCTRADE_SECOND_HIDDENTAB			1308
#define _XDEF_NPCTRADE_SECOND_MUSICTAB			1309
#define _XDEF_NPCTRADE_LISTBOX					1310
#define _XDEF_NPCTRADE_BUYOK					1311
#define _XDEF_NPCTRADE_BUYNO					1312
#define _XDEF_NPCTRADE_SELLOK					1313
#define _XDEF_NPCTRADE_SELLNO					1314
#define _XDEF_NPCTRADE_HELP						1315
#define _XDEF_NPCTRADE_ONE						1316
#define _XDEF_NPCTRADE_TWO						1317
#define _XDEF_NPCTRADE_THREE					1318
#define _XDEF_NPCTRADE_FOUR						1319
#define _XDEF_NPCTRADE_FIVE						1320

#define _XDEF_WTITLE_MAINMENUWINDOW				10035 //_T("MainMenu")
#define _XDEF_MAINMENU_MAINWINDOW				1400
#define _XDEF_MAINMENU_INVENTORY				1401
#define _XDEF_MAINMENU_OPTION					1402
#define _XDEF_MAINMENU_HEDEK					1403
#define _XDEF_MAINMENU_MESSENGER				1404
#define _XDEF_MAINMENU_EMAIL					1405
#define _XDEF_MAINMENU_MEDBUTTON				1406
#define _XDEF_MAINMENU_BTN_CASHMALL				1407
#define _XDEF_MAINMENU_BTN_CASHBOX				1408

#define _XDEF_MAINMENU_SKILL					1403
#define _XDEF_MAINMENU_LIFE						1404
#define _XDEF_MAINMENU_QUEST					1405
#define _XDEF_MAINMENU_COMMUNITY				1406
#define _XDEF_MAINMENU_MINIMAP					1407
#define _XDEF_MAINMENU_SYSTEMMENU				1408

#define _XDEF_WTITLE_TRADECONFIRM				10036 //_T("TradeConfirm")
#define _XDEF_TRADECONFIRM_CLOSE				1500
#define _XDEF_TRADECONFIRM_OK					1501
#define _XDEF_TRADECONFIRM_ALL					1502

#define _XDEF_WTITLE_REQUESTPARTY				10038 //_T("RequestParty")
#define _XDEF_REQUESTPARTY_CLOSE				1600
#define _XDEF_REQUESTPARTY_SENDMESSAGE			1601
#define _XDEF_REQUESTPARTY_REQUESTPARTY			1602
#define _XDEF_REQUESTPARTY_JOINPARTYOK			1603
#define _XDEF_REQUESTPARTY_JOINPARTYNO			1604
#define _XDEF_REQUESTPARTY_REQUESTTRADE			1605
#define _XDEF_REQUESTPARTY_REQUESTFRIEND		1606	
#define _XDEF_REQUESTPARTY_FRIENDOK				1607	
#define _XDEF_REQUESTPARTY_FRIENDNO				1608	
#define _XDEF_REQUESTPARTY_JOINBOSSBATTLE		1609	
#define _XDEF_REQUESTPARTY_REQUESTBOSSBATTLE	1610	
#define _XDEF_REQUESTPARTY_SOLOBOSSBATTLE		1611
#define _XDEF_REQUESTPARTY_REQPVP				1612
#define _XDEF_REQUESTPARTY_REQGROUP				1613
#define _XDEF_REQUESTPARTY_REQPVPGROUP			1614
#define _XDEF_REQUESTPARTY_REQALIENCE			1615
#define _XDEF_REQUESTPARTY_REQMASTERNDISCIPLE	1616

#define _XDEF_WTITLE_MESSENGERWINDOW			10039 //_T("Messenger")
#define _XDEF_MESSENGERWINDOW_CLOSEBUTTON		 1701 
#define _XDEF_MESSENGERWINDOW_HELPBUTTON		 1702 
#define _XDEF_MESSENGERWINDOW_MESSENGERLOGIN	 1703  
#define _XDEF_MESSENGERWINDOW_MESSENGERLOGOUT	 1704 
#define _XDEF_MESSENGERWINDOW_ADDFRIENDBUTTON	 1705
#define _XDEF_MESSENGERWINDOW_ADDGROUPBUTTON	 1706 
#define _XDEF_MESSENGERWINDOW_CHANGESTATUSBUTTON 1707
#define _XDEF_MESSENGERWINDOW_LISTBOX		 	 1708 
#define _XDEF_MESSENGERWINDOW_RECALLBUTTON		1709 //Author : 양희왕 //breif : 친구소환

#define _XDEF_WTITLE_JINSTATUSWINDOW			10040 //_T("Jin")
#define _XDEF_JINSTATUS_LEVELUPBUTTON			1720 //2004.06.24->oneway48 insert
#define _XDEF_JINSTATUS_CONVERGENCEBUTTON		1721
#define _XDEF_JINSTATUS_ABILITYUPBUTTON			1722
#define _XDEF_JINSTATUS_SHUTDOWNONOFFBUTTON		1723

#define _XDEF_WTITLE_MONSTERSTATUSWINDOW		10041 //_T("Monster")
#define _XDEF_MONSTERSTATUS_CLOSEBUTTON			1730
#define _XDEF_MONSTERSTATUS_FUNCTIONBUTTON1		1731
#define _XDEF_MONSTERSTATUS_FUNCTIONBUTTON2		1732
#define _XDEF_MONSTERSTATUS_FUNCTIONBUTTON3		1733
#define _XDEF_MONSTERSTATUS_POPUPBUTTON1		1734
#define _XDEF_MONSTERSTATUS_POPUPBUTTON2		1735
#define _XDEF_MONSTERSTATUS_POPUPBUTTON1YES		1736
#define _XDEF_MONSTERSTATUS_POPUPBUTTON1NO		1737
#define _XDEF_MONSTERSTATUS_POPUPBUTTON2YES		1738
#define _XDEF_MONSTERSTATUS_POPUPBUTTON2NO		1739
#define _XDEF_MONSTERSTATUS_INFOPOPUPBUTTON1	1740
#define _XDEF_MONSTERSTATUS_INFOPOPUPBUTTON2	1741
#define _XDEF_MONSTERSTATUS_INFOPOPUPBUTTON3	1742
#define _XDEF_MONSTERSTATUS_INFOPOPUPBUTTON4	1743
#define _XDEF_MONSTERSTATUS_INFOPOPUPYES		1744
#define _XDEF_MONSTERSTATUS_INFOPOPUPNO			1745
#define _XDEF_MONSTERSTATUS_INFOPOPUPCANCLE		1746

#define _XDEF_WTITLE_ZONENAMEWINDOW				10042 //_T("ZoneName")

#define _XDEF_WTITLE_DEATHBLOWWINDOW			10043 //_T("DeathBlow")
#define _XDEF_DEATHBLOW_LEFTBLOWBUTTON			1900
#define _XDEF_DEATHBLOW_RIGHTBLOWBUTTON			1901

#define _XDEF_WTITLE_TRADETOOLTIP				10044 //_T("TradeItemTooltip")

#define _XDEF_WTITLE_SELECTSERVERFOREST 		10045 //_T("SelectServerForestWindow")

#define _XDEF_WTITLE_ZOOM						10049 //_T("ZoomWindow")
#define _XDEF_WTITLE_ROTATE						10050 //_T("RotateWindow")

#define _XDEF_WTITLE_SELECTSERVER				10051 //_T("SelectServerWindow")
#define _XDEF_SELECTSERVERLISTCTRL				2000

#define _XDEF_GAMECLOSE							2100
#define _XDEF_CANCELGAMECLOSE					2101
#define _XDEF_PROCESSTOPSIGNAL					2102
#define _XDEF_GOTOSELECTCHARACTER				2103
#define _XDEF_GOTOLOGINSERVER					2104

#define _XDEF_WTITLE_XDEBUGWINDOW				10051 //_T("XDebug")
#define _XDEF_XDEBUGINFOMODE_BASE				3000		
#define _XDEF_XDEBUGINFOMODE_SYSTEM				3001
#define _XDEF_XDEBUGINFOMODE_VIDEOINFO			3002
#define _XDEF_XDEBUGINFOMODE_WORLD				3003

#define _XDEF_WTITLE_NOTICEWINDOW				10052 //_T("Notice")
#define _XDEF_NOTICEWINDOW_CLOSEBUTTON			3100

#define _XDEF_WTITLE_CHARGEGAUGE				10053 // _T("Charge Gauge")

#define _XDEF_WTITLE_WAREHOUSE					10054 //_T("Warehouse")
#define _XDEF_WAREHOUSEWINDOW_CLOSE				3300
#define _XDEF_WAREHOUSEWINDOW_HELP				3301
#define _XDEF_WAREHOUSEWINDOW_SENDADDITEM		3302
#define _XDEF_WAREHOUSEWINDOW_ALLSELECT			3303
#define _XDEF_WAREHOUSEWINDOW_STORAGEMONEY		3304
#define _XDEF_WAREHOUSEWINDOW_INVENTORYMONEY	3305
#define _XDEF_WAREHOUSEWINDOW_ONE				3306
#define _XDEF_WAREHOUSEWINDOW_TWO				3307
#define _XDEF_WAREHOUSEWINDOW_THREE				3308
#define _XDEF_WAREHOUSEWINDOW_REMOVAL			3309


#define _XDEF_WTITLE_ADDSAVEITEM				10055 //_T("AddSaveItem")
#define _XDEF_ADDSAVEITEMWINDOW_CLOSE			3400
#define _XDEF_ADDSAVEITEMWINDOW_HELP			3401
#define _XDEF_ADDSAVEITEMWINDOW_OK				3402
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN1		3403 
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN2		3404
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN3		3405
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN4		3406
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN5		3407
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN6		3408
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN7		3409
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN8		3410
#define _XDEF_ADDSAVEITEMWINDOW_CHECKBTN9		3411 
#define _XDEF_ADDSAVEITEMWINDOW_POCKET1			3412 //Author : 양희왕 //breif : 창고확장
#define _XDEF_ADDSAVEITEMWINDOW_POCKET2			3413

#define _XDEF_WTITLE_MESSENGERTOOLTIPWINDOW					10056 //_T("MessengerTooltip")
#define _XDEF_MESSENGERTOOLTIPWINDOW_CLOSEBUTTON			3500
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEFRIENDBUTTON		3501
#define _XDEF_MESSENGERTOOLTIPWINDOW_ADDGROUPBUTTON			3502
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEGROUPBUTTON		3503
#define _XDEF_MESSENGERTOOLTIPWINDOW_CHANGERGROUPNAMEBUTTON	3504
#define _XDEF_MESSENGERTOOLTIPWINDOW_STATUSLISTBOX			3505
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEGROUPOK			3506
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEGROUPNO			3507
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEFRIENDOK			3508
#define _XDEF_MESSENGERTOOLTIPWINDOW_DELETEFRIENDNO			3509
#define _XDEF_MESSENGERTOOLTIPWINDOW_CHATFUNCTIONLISTBOX	3510
#define _XDEF_MESSENGERTOOLTIPWINDOW_CHATRECENTLISTBOX		3511

#define _XDEF_WTITLE_NAMEINPUTWINDOW			10057 //_T("NameInput") 
#define _XDEF_NAMEINPUTWINDOW_CLOSE				3600
#define _XDEF_NAMEINPUTWINDOW_OK				3601

#define _XDEF_WTITLE_NPCSKILL						10058 //_T("NPCSkill")
#define _XDEF_NPCSKILLWINDOW_LISTBOX				3700
#define _XDEF_NPCSKILLWINDOW_REQLEARNSKILL			3701
#define _XDEF_NPCSKILLWINDOW_HELP					3702
#define _XDEF_NPCSKILLWINDOW_LEFT					3703
#define _XDEF_NPCSKILLWINDOW_RIGHT					3704
#define _XDEF_NPCSKILLWINDOW_REQLEARNSKILLBUTTON	3705
#define _XDEF_NPCSKILLWINDOW_SKILL_1				3706
#define _XDEF_NPCSKILLWINDOW_SKILL_2				3707
#define _XDEF_NPCSKILLWINDOW_SKILL_3				3708
#define _XDEF_NPCSKILLWINDOW_SKILL_4				3709
#define _XDEF_NPCSKILLWINDOW_SKILL_5				3710
#define _XDEF_NPCSKILLWINDOW_SKILL_6				3711
#define _XDEF_NPCSKILLWINDOW_SKILL_7				3712
#define _XDEF_NPCSKILLWINDOW_SKILL_8				3713

#define _XDEF_WTITLE_NPCSKILLTOOLTIP				10059 //_T("NPCSkillTooltip")

#define _XDEF_WTITLE_REBIRTH						10060 // _T("Rebirth")
#define _XDEF_REBIRTHWINDOW_TOWN					3800
#define _XDEF_REBIRTHWINDOW_FIELD					3801
#define _XDEF_REBIRTHWINDOW_USEITEM					3802
#define _XDEF_REBIRTHWINDOW_SAVEPOINT				3803
#define _XDEF_REBIRTHWINDOW_HELP					3804
#define _XDEF_REBIRTHWINDOW_ACCLAIMVIDEOAD			3805
#define _XDEF_REBIRTHWINDOW_INCB					3806

// 2004.06.17->oneway48 insert
#define _XDEF_WTITLE_REPAIRITEM						10061 // _T("Repair Item")
#define _XDEF_REPAIRITEMWINDOW_ALLBUTTON			3900
#define _XDEF_REPAIRITEMWINDOW_REPAIRBUTTON			3901
#define _XDEF_REPAIRITEMWINDOW_CANCLE				3902
#define _XDEF_REPAIRITEMWINDOW_ALLREPAIRYES			3903
#define _XDEF_REPAIRITEMWINDOW_ALLREPAIRNO			3904
#define _XDEF_REPAIRITEMWINDOW_CLOSE				3905
#define _XDEF_REPAIRITEMWINDOW_HELP					3906
#define _XDEF_REPAIRITEMWINDOW_SELECTEDALL			3907
#define _XDEF_REPAIRITEMWINDOW_SELECTEDCANCLE		3908
#define _XDEF_REPAIRITEMWINDOW_LISTBOX				3908

// insert

#define _XDEF_WTITLE_MEDITATION						10062 // _T("Meditation(Minigame))" 2004.06.15->hotblood
#define _XDEF_MEDITATION_YES						4001
#define _XDEF_MEDITATION_NO							4002
#define _XDEF_MEDITATION_START						4003
#define _XDEF_MEDITATION_EXIT						4004
#define _XDEF_MEDITATION_HELP						4005

#define _XDEF_WTITLE_HELP							10064 // hotblood

#define _XDEF_WTITLE_TRAININGMEDITATION				10065  // _T("Training Meditation")
#define _XDEF_TRAINING_MEDITATION_START				4100
#define _XDEF_TRAINING_MEDITATION_EXIT				4101
#define _XDEF_TRAINING_MEDITATION_HELP				4102

#define _XDEF_WTITLE_TRAININGDUMMY					10066	// _T("Training Dummy")
#define _XDEF_TRAINING_DUMMY_START					4200
#define _XDEF_TRAINING_HELP_CLOSE					4201

#define _XDEF_TRAINING_CANCEL_OK					4202
#define _XDEF_TRAINING_CANCEL_NO					4203

#define _XDEF_WTITLE_TRAININGSPELL					10067	// "Training Spell"
#define _XDEF_TRAINING_SPELL_START					4204

#define _XDEF_WTITLE_ENTERBOSSROOM					10068	// "Enter Boss Room"
#define _XDEF_BOSSROOM_ENTER						4301
#define _XDEF_BOSSROOM_CANCLE						4302
#define _XDEF_BOSSROOM_ENTEROK						4303
#define _XDEF_BOSSROOM_ASKPARTYMEMBER				4304
#define _XDEF_BOSSROOM_USEITEMCANCEL				4305

#define _XDEF_WTITLE_ZEROLEVEL						10069 // "zerolevel"
#define _XDEF_ZEROLEVEL_START						4401
#define _XDEF_ZEROLEVEL_SKIP						4402 

#define _XDEF_WTITLE_NICKNAME						10070 // "nickname"
#define _XDEF_NICKNAME_APPLY						4501
#define _XDEF_NICKNAME_NOTAPPLY						4502
#define _XDEF_NICKNAME_DELETE						4503
#define _XDEF_NICKNAME_SPECIALNICKNAMELIST			4504
#define _XDEF_NICKNAME_GENERALNICKNAMEIST			4505
#define _XDEF_NICKNAME_UNIQUENICKNAMEIST			4506
#define _XDEF_NICKNAME_CLOSE						4507
#define _XDEF_NICKNAME_HELP							4508
#define _XDEF_NICKNAME_DELETE_YES					4509
#define _XDEF_NICKNAME_DELETE_NO					4510
#define _XDEF_NICKNAME_RANKHIDING					4511

#define _XDEF_WTITLE_SOCKETPLUGIN					10073	// "socketplugin" 2004.11.3->hotblood insert
#define _XDEF_SOCKETPLUGIN_APPLY					4801
#define _XDEF_SOCKETPLUGIN_CANCLE					4802
#define _XDEF_SOCKETPLUGIN_APPLYOK					4803
#define _XDEF_SOCKETPLUGIN_APPLYCANCLE				4804
#define _XDEF_SOCKETPLUGIN_CHANGEOK					4805
#define _XDEF_SOCKETPLUGIN_CHANGECANCLE				4806
#define _XDEF_SOCKETPLUGIN_CLOSEOK					4807
#define _XDEF_SOCKETPLUGIN_CLOSECANCLE				4808
#define _XDEF_SOCKETPLUGIN_CLOSE					4809
#define _XDEF_SOCKETPLUGIN_HELP						4810

#define _XDEF_WTITLE_MAINFRAME						10074	// main frame window
#define _XDEF_MAINFRAME_CLOSEBUTTON					4820
#define _XDEF_MAINFRAME_HELPBUTTON					4821
#define _XDEF_MAINFRAME_CHARACTORTAB				4822
#define _XDEF_MAINFRAME_PKRECORDTAB					4823
#define _XDEF_MAINFRAME_MASTERYTAB					4824
#define _XDEF_MAINFRAME_SKILLTAB					4825
#define _XDEF_MAINFRAME_LIFETAB						4826
#define _XDEF_MAINFRAME_QUESTTAB					4827
#define _XDEF_MAINFRAME_COMMUNITYTAB				4828

#define _XDEF_WTITLE_MASTERYSKILL					10075	// "오의"
#define _XDEF_MASTERYSKILL_CLASS_1					4830
#define _XDEF_MASTERYSKILL_CLASS_2					4831
#define _XDEF_MASTERYSKILL_CLASS_3					4832
#define _XDEF_MASTERYSKILL_CLASS_4					4833
#define _XDEF_MASTERYSKILL_APPLYOK					4834
#define _XDEF_MASTERYSKILL_APPLYCANCLE				4835

#define _XDEF_WTITLE_SYSTEMMSGDEFAULT				10076	// System Message Window
#define _XDEF_SYSTEMMSGDEFAULT_CLOSE				4901
#define _XDEF_FUNCTONIONALOBJRECTVIEW_CLOSE			4902	//Functional Object View Close

#define _XDEF_WTITLE_OPTIONMENU						10077 //_T("Option menu")
#define _XDEF_OPTIONMENU_CLOSEBUTTON				4910
#define _XDEF_OPTIONMENU_HELPBUTTON					4911

#define _XDEF_OPTIONMENU_GRAPHICTABBUTTON			4912
#define _XDEF_OPTIONMENU_SOUNDTABBUTTON				4913
#define _XDEF_OPTIONMENU_GAMETABBUTTON				4914
#define _XDEF_OPTIONMENU_COMMUNITYTABBUTTON			4915
#define _XDEF_OPTIONMENU_ANOTHORUSERTABBUTTON		4916
#define _XDEF_OPTIONMENU_GOTOLOGINTABBUTTON			4917
#define _XDEF_OPTIONMENU_EXITGAMETABBUTTON			4918

#define _XDEF_WTITLE_DEFAULTTOOLTIP					10078	// Default Tooltip window
#define _XDEF_WTITLE_DT_DELECTSKILLBTN				4990
#define _XDEF_WTITLE_DT_DELECTSKILLSTEP1YES			4991
#define _XDEF_WTITLE_DT_DELECTSKILLSTEP2YES			4992
#define _XDEF_WTITLE_DT_DELECTSKILLSTEP3YES			4993
					
#define _XDEF_WTITLE_EMAILWINDOW					10079 //_T("Messenger Email")
#define _XDEF_EMAILWINDOW_EMAILRECEIVEBOX			5000 
#define _XDEF_EMAILWINDOW_EMAILSENDBOX				5001 
#define _XDEF_EMAILWINDOW_EMAILKEEPBOX				5002 
#define _XDEF_EMAILWINDOW_EMAILCLOSE				5003 
#define _XDEF_EMAILWINDOW_EMAILHELP					5004
#define _XDEF_EMAILWINDOW_EMAILNEXT					5005 
#define _XDEF_EMAILWINDOW_EMAILPREV					5006
#define _XDEF_EMAILWINDOW_EMAILKEEPINGMAILDELETE	5007
#define _XDEF_EMAILWINDOW_EMAILRECEIVEREPLY			5008
#define _XDEF_EMAILWINDOW_EMAILRECEIVESAVE			5009
#define _XDEF_EMAILWINDOW_EMAILRECEIVEDELETE		5010 
#define _XDEF_EMAILWINDOW_EMAILSENDDELETE			5011 
#define _XDEF_EMAILWINDOW_EMAILSENDCANCLE			5012 
#define _XDEF_EMAILWINDOW_EMAILSEND					5013  


#define _XDEF_WTITLE_MESSENGERDIALOGWINDOW			10080 //_T("Messenger")
#define _XDEF_MESSENGERDIALOGWINDOW_HELP			5020 
#define _XDEF_MESSENGERDIALOGWINDOW_MINIMIZE		5021 
#define _XDEF_MESSENGERDIALOGWINDOW_CLOSE			5022 
#define _XDEF_MESSENGERDIALOGWINDOW_INFORMATION		5023 
#define _XDEF_MESSENGERDIALOGWINDOW_PARTYREQUEST	5024
#define _XDEF_MESSENGERDIALOGWINDOW_FRIENDCUT		5025 
#define _XDEF_MESSENGERDIALOGWINDOW_CHATINPUT		5026
#define _XDEF_MESSENGERDIALOGWINDOW_EMOTICON		5027

#define _XDEF_WTITLE_STATEWINDOW					10081	// _T("State Window")
#define _XDEF_STATEWINDOW_STATECANCLEYES			5035
#define _XDEF_STATEWINDOW_STATECANCLENO				5036

#define _XDEF_WTITLE_CONTRIBUTIONWINDOW				10082	// _T("Contribution Window")
#define _XDEF_CONTRIWINDOW_CLOSEBUTTON				5040
#define _XDEF_CONTRIWINDOW_HELPBUTTON				5041
#define _XDEF_CONTRIWINDOW_APPLYBUTTON				5042
#define _XDEF_CONTRIWINDOW_CANCLE					5043

#define _XDEF_CHATDEFAULT_EMOTION1					5060	// Emotion list 5060 ~ 5089
#define _XDEF_CHATDEFAULT_EMOTION2					5061
#define _XDEF_CHATDEFAULT_EMOTION3					5062
#define _XDEF_CHATDEFAULT_EMOTION4					5063
#define _XDEF_CHATDEFAULT_EMOTION5					5064
#define _XDEF_CHATDEFAULT_EMOTION6					5065
#define _XDEF_CHATDEFAULT_EMOTION7					5066
#define _XDEF_CHATDEFAULT_EMOTION8					5067
#define _XDEF_CHATDEFAULT_EMOTION9					5068
#define _XDEF_CHATDEFAULT_EMOTION10					5069

#define _XDEF_WTITLE_TRAININGHELP					10083	// _T("Training Help Window")
#define _XDEF_TRAINING_HELP_START					5090
#define _XDEF_TRAINING_HELP_END						5091
#define _XDEF_TRAINING_HELP_LEFT					5092
#define _XDEF_TRAINING_HELP_RIGHT					5093

#define _XDEF_TRAINING_HELP_SKILL_1					5094
#define _XDEF_TRAINING_HELP_SKILL_2					5095
#define _XDEF_TRAINING_HELP_SKILL_3					5096
#define _XDEF_TRAINING_HELP_SKILL_4					5097
#define _XDEF_TRAINING_HELP_SKILL_5					5098
#define _XDEF_TRAINING_HELP_SKILL_6					5099
#define _XDEF_TRAINING_HELP_SKILL_7					5100
#define _XDEF_TRAINING_HELP_SKILL_8					5101

#define _XDEF_WTITLE_HEDEK							10084	// _T("Hedek Window")
#define _XDEF_HEDEK_HEDEKLISTBOX					5130
#define _XDEF_HEDEK_CLOSE							5131
#define _XDEF_HEDEK_HELPBOOKCALL					5132

#define _XDEF_WTITLE_POCKET							10085	// _T("Pocket Window")
#define _XDEF_POCKET_HELP							5160
#define _XDEF_POCKET_CLOSE							5161
#define _XDEF_POCKET_CLOSEOK						5162
#define _XDEF_POCKET_CLOSECANCLE					5163

#define _XDEF_WTITLE_TUTORIALICON					10086	// _T("Tutorial Window")
#define _XDEF_TUTORIAL_ICON1						5201
#define _XDEF_TUTORIAL_ICON2						5202
#define _XDEF_TUTORIAL_ICON3						5203
#define _XDEF_TUTORIAL_ICON4						5204
#define _XDEF_TUTORIAL_ICON5						5205
#define _XDEF_TUTORIAL_ICON6						5206
#define _XDEF_TUTORIAL_ICON7						5207
#define _XDEF_TUTORIAL_ICON8						5208

#define _XDEF_WTITLE_HELPBOOK						10087	// _T("Help book Window")
#define _XDEF_HELPBOOK_HELPLIST						5220
#define _XDEF_HELPBOOK_CLOSE						5221
#define _XDEF_HELPBOOK_LEFTSTEP						5222
#define _XDEF_HELPBOOK_RIGHTSTEP					5223

#define _XDEF_WTITLE_GMWINDOW						10088
#define _XDEF_GMWINDOW_OPENBUTTON					5300
#define _XDEF_GMWINDOW_COMMANDBUTTON0				5301
#define _XDEF_GMWINDOW_COMMANDBUTTON1				5302
#define _XDEF_GMWINDOW_COMMANDBUTTON2				5303
#define _XDEF_GMWINDOW_COMMANDBUTTON3				5304
#define _XDEF_GMWINDOW_COMMANDBUTTON4				5305
#define _XDEF_GMWINDOW_COMMANDBUTTON5				5306
#define _XDEF_GMWINDOW_COMMANDBUTTON6				5307
#define _XDEF_GMWINDOW_COMMANDBUTTON7				5308
#define _XDEF_GMWINDOW_COMMANDBUTTON8				5309
#define _XDEF_GMWINDOW_COMMANDBUTTON9				5310

#define _XDEF_WTITLE_GMCHARACTERSETTINGWINDOW		10089
#define _XDEF_GMCHARACTERSETTINGWINDOWCLOSEBTN		5320
#define _XDEF_GMSTATUSCONTROLHIDDENBUTTON			5321
#define _XDEF_GMSTATUSCONTROLCAMERASPEEDSLIDER		5322
#define _XDEF_GMSTATUSCONTROLFOGDISTANCESLIDER		5323
#define _XDEF_GMSTATUSCONTROLENVIRONMENTSLIDER		5324
#define _XDEF_GMSTATUSCONTROLTIMEFLOWCHECKBUTTON	5325
#define _XDEF_GMSTATUSCONTROLFLYCAMMODE				5326
#define _XDEF_GMSTATUSCONTROLCURSORVIEW				5327

#define _XDEF_WTITLE_GMCHARACTERCOORDSETTINGWINDOW	10090
#define _XDEF_GMCHARACTERCOORDSETTINGWINDOWCLOSEBTN	5330
#define _XDEF_GMCHARACTERCOORDSETTINGGMMOVE			5332
#define _XDEF_GMCHARACTERCOORDSETTINGGMMOVETOUSER	5333
#define _XDEF_GMCHARACTERCOORDSETTINGMOVEUSER		5334

#define _XDEF_WTITLE_GMCHARACTERINFOSETTINGWINDOW	10091
#define _XDEF_GMCHARACTERINFOSETTINGWINDOWCLOSEBTN	5340

#define _XDEF_WTITLE_GMUSERMANAGEMENTWINDOW			10092
#define _XDEF_GMUSERMANAGEMENTWINDOWCLOSEBTN		5350

#define _XDEF_WTITLE_GMCONSULTATIONWINDOW			10093
#define _XDEF_GMCONSULTATIONWINDOWCLOSEBTN			5360

#define _XDEF_WTITLE_GMNOTICEMESSAGEWINDOW			10094
#define _XDEF_GMNOTICEMESSAGEWINDOWCLOSEBTN			5370
#define _XDEF_GMNOTICEMESSAGEWINDOWMESSAGELIST		5371
#define _XDEF_GMNOTICEMESSAGEINSERTBTN				5372
#define _XDEF_GMNOTICEMESSAGEDELETEBTN				5373
#define _XDEF_GMNOTICEMESSAGECONFIRMDELETE			5374
#define _XDEF_GMNOTICEMESSAGEDELETEALLBTN			5375
#define _XDEF_GMNOTICEMESSAGECONFIRMDELETEALL		5376

#define _XDEF_WTITLE_GMCONTROLMONSTERWINDOW			10095
#define _XDEF_GMCONTROLMONSTERWINDOWCLOSEBTN		5380
#define _XDEF_GMMONSTERSPAWNBUTTON					5381	
#define _XDEF_GMMONSTERSPAWN_MOBLISTBOX				5382

#define _XDEF_WTITLE_GMEVENTCONTROLWINDOW			10096
#define _XDEF_GMEVENTCONTROLWINDOWCLOSEBTN			5390
#define _XDEF_GMEVENTCONTROLWINDOW_BGM1				5391
#define _XDEF_GMEVENTCONTROLWINDOW_BGM2				5392
#define _XDEF_GMEVENTCONTROLWINDOW_BGM3				5393
#define _XDEF_GMEVENTCONTROLWINDOW_BGMSTOP			5394
#define _XDEF_GMEVENTCONTROLWINDOW_FIREWORK			5395
#define _XDEF_GMEVENTCONTROLWINDOW_FLOWER1			5396
#define _XDEF_GMEVENTCONTROLWINDOW_FLOWER2			5397
#define _XDEF_GMEVENTCONTROLWINDOW_FLOWER3			5398
#define _XDEF_GMEVENTCONTROLWINDOW_WEDDINGSTAGE		5399
#define _XDEF_GMEVENTCONTROLWINDOW_WEDDINGSTAGEEND	5400
#define _XDEF_GMEVENTCONTROLWINDOW_ENVDAY			5401
#define _XDEF_GMEVENTCONTROLWINDOW_NIGHTFALL		5402
#define _XDEF_GMEVENTCONTROLWINDOW_NIGHT			5403

#define _XDEF_WTITLE_GMDEBUGCOMMANDWINDOW			10097
#define _XDEF_GMDEBUGCOMMANDWINDOWCLOSEBTN			5405

#define _XDEF_WTITLE_GMCOMMANDLOGWINDOW				10098
#define _XDEF_GMCOMMANDLOGWINDOWCLOSEBTN			5410


//////////////////////////////////////////////////////////////////////////
// Command ID GM Command용으로 5499 까지 예약 이후에는 5500부터 시작할것.
//////////////////////////////////////////////////////////////////////////

#define _XDEF_WTITLE_GROUPWINDOW					10200	// _T("Group Window")
#define _XDEF_GROUP_ORGANIZATION					5500	//영웅단 탭 버튼
#define _XDEF_GROUP_ORGANIZATION_LEAVEBTN			5501
#define _XDEF_GROUP_ORGANIZATION_LINELEVEL			5502
#define _XDEF_GROUP_ORGANIZATION_LINEZONE			5503
#define _XDEF_GROUP_ORGANIZATION_LINECONNECT		5504
#define _XDEF_GROUP_ORGANIZATION_LISTBOX			5505
#define _XDEF_GROUP_ORGANIZATION_CREATEYES			5506
#define _XDEF_GROUP_ORGANIZATION_CREATENO			5507
#define _XDEF_GROUP_ORGANIZATION_NAMECOMPLETE		5508
#define _XDEF_GROUP_ORGANIZATION_NAMECANCLE			5509
#define _XDEF_GROUP_ORGANIZATION_FRIEND				5510
#define _XDEF_GROUP_ORGANIZATION_EMAIL				5511
#define _XDEF_GROUP_ORGANIZATION_WHISPER			5512
#define _XDEF_GROUP_ORGANIZATION_PARTY				5513
#define _XDEF_GROUP_ORGANIZATION_GRANT				5514
#define _XDEF_GROUP_ORGANIZATION_GRANTCANCLE		5515
#define _XDEF_GROUP_ORGANIZATION_TRUST				5516
#define _XDEF_GROUP_ORGANIZATION_PRUGE				5517
#define _XDEF_GROUP_ORGANIZATION_INVITE_OK			5518
#define _XDEF_GROUP_ORGANIZATION_INVITE_NO			5519
#define _XDEF_GROUP_ORGANIZATION_ENTRUST_OK			5520
#define _XDEF_GROUP_ORGANIZATION_ENTRUST_NO			5521
#define _XDEF_GROUP_ORGANIZATION_LEAVE_OK			5522
#define _XDEF_GROUP_ORGANIZATION_LEAVE_NO			5523
#define _XDEF_GROUP_ORGANIZATION_SORTBTN			5524
#define _XDEF_GROUP_ORGANIZATION_SORTLIST			5525
#define _XDEF_GROUP_ORGANIZATION_NOTICEWRITE		5526
#define _XDEF_GROUP_ORGANIZATION_NOTICEMODIFY		5527
#define _XDEF_GROUP_ORGANIZATION_WRITEFINISH		5528
#define _XDEF_GROUP_ORGANIZATION_WRITECANCLE		5529
#define _XDEF_GROUP_ALIENCE_ALIENCETAB				5530	//영웅단회 탭 버튼
#define _XDEF_GROUP_ALIENCE_ALIENCEDESTROY			5531	//영웅단 동맹 파기 버튼
#define _XDEF_GROUP_ALIENCE_BTN_ALIENCEMEMBER1		5532	//영웅단 동맹 멤버버튼 1
#define _XDEF_GROUP_ALIENCE_BTN_ALIENCEMEMBER2		5533	//영웅단 동맹 멤버버튼 2
#define _XDEF_GROUP_ALIENCE_BTN_ALIENCEMEMBER3		5534	//영웅단 동맹 멤버버튼 3
#define _XDEF_GROUP_ALIENCE_BTN_ALIENCEMEMBER4		5535	//영웅단 동맹 멤버버튼 4
#define _XDEF_GROUP_ALIENCE_BTN_ALIENCEMEMBER5		5536	//영웅단 동맹 멤버버튼 5
#define _XDEF_GROUP_ALIENCE_BTN_INVITE_OK			5537	//영웅단 동맹 수락 OK
#define _XDEF_GROUP_ALIENCE_BTN_INVITE_NO			5538	//영웅단 동맹 수락 NO
#define _XDEF_GROUP_CASTLEBATTLE_CASTLEBATTLETAB	5539	//장원 탭 버튼
#define _XDEF_GROUP_CASTLEBATTLE_BTN_TIMECHANGE		5540	//장원전 시간 변경 버튼
#define _XDEF_GROUP_CASTLEBATTLE_BTN_GETMONEY		5541	//보유금 획득 버튼
#define _XDEF_GROUP_CASTLEBATTLE_WARSITUATIONTAB	5542	//장원전황 탭 버튼
#define _XDEF_GROUP_CHALLENGER_LISTBOX				5543	// 도전자 목록
#define _XDEF_GROUP_ALIENCE_BTN_GOTOORGANIZATION	5544	//영웅단 게시판 바로가기 버튼
#define _XDEF_GROUP_ALIENCE_BTN_GOTOALIENCE			5545	//영웅회 게시판 바로가기 버튼
#define _XDEF_GROUP_CASTLEBATTLE_ORGRECORD			5546	// 장원전황 - 대전 기록
#define _XDEF_GROUP_MASTERNDISCIPLETAB				5547	//Author : 양희왕 //breif : 사제 탭 버튼
#define _XDEF_GROUP_MASTERNDISCIPLE_LEAVEBTN		5548	//Author : 양희왕 //breif : 하산 버튼
#define _XDEF_GROUP_MASTERNDISCIPLE_NOTICEWRITE		5549	//Author : 양희왕 //breif : 글쓰기 버튼
#define _XDEF_GROUP_MASTERNDISCIPLE_NOTICEMODIFY	5590	//Author : 양희왕 //breif : 수정 버튼 //헉,, 남는게 없다,, 90번부터 쓰겠다.
#define _XDEF_GROUP_MASTERNDISCIPLE_LISTBOX			5591	//Author : 양희왕 //breif : 사제정보 리스트박스
#define _XDEF_GROUP_MASTERNDISCIPLE_EMAIL			5592	//Author : 양희왕 //breif : 전서구 보내기
#define _XDEF_GROUP_MASTERNDISCIPLE_WHISPER			5593	//Author : 양희왕 //breif : 귓속말 보내기
#define _XDEF_GROUP_MASTERNDISCIPLE_PARTY			5594	//Author : 양희왕 //breif : 동행 맺기
#define _XDEF_GROUP_MASTERNDISCIPLE_PURGE			5595	//Author : 양희왕 //breif : 추방
#define _XDEF_GROUP_MASTERNDISCIPLE_WRITEFINISH		5596
#define _XDEF_GROUP_MASTERNDISCIPLE_WRITECANCLE		5597

#define _XDEF_WTITLE_PERSONALSTORE					10201 // _T("Personal Store Window") 개인 상점
#define _XDEF_PERSONALSTORE_HELPBUTTON				5550 
#define _XDEF_PERSONALSTORE_CLOSEBUTTON				5551 
#define _XDEF_PERSONALSTORE_OPENBUTTON				5552 
#define _XDEF_PERSONALSTORE_CANCLEBUTTON			5553 
#define _XDEF_PERSONALSTORE_BUYOK					5554 
#define _XDEF_PERSONALSTORE_BUYNO					5555
#define _XDEF_PERSONALSTORE_INPUTOKBUTTON			5556 

#define _XDEF_WTITLE_LIFESKILL						10202	// "생활"
#define _XDEF_LIFESKILL_USEBUTTON					5560 //개인상점 버튼
#define _XDEF_LIFESKILL_PVPPRBUTTON					5561 //비무홍보버튼
#define _XDEF_LIFESKILL_CLASSBUTTON1				5562
#define _XDEF_LIFESKILL_CLASSBUTTON2				5563
#define _XDEF_LIFESKILL_CLASSBUTTON3				5564
#define _XDEF_LIFESKILL_CLASSBUTTON4				5565
#define _XDEF_LIFESKILL_CLASSBUTTON5				5566
#define _XDEF_LIFESKILL_TYPEBUTTON1					5567
#define _XDEF_LIFESKILL_TYPEBUTTON2					5568
#define _XDEF_LIFESKILL_TYPEBUTTON3					5569
#define _XDEF_LIFESKILL_TYPEBUTTON4					5570
#define _XDEF_LIFESKILL_TYPEBUTTON5					5571
#define _XDEF_LIFESKILL_TYPEBUTTON6					5572
#define _XDEF_LIFESKILL_COLLECTIONLISTBOX			5573
#define _XDEF_LIFESKILL_RESOURCELISTBOX				5574
#define _XDEF_LIFESKILL_RESOURCENEEDITEMLISTBOX		5575
#define _XDEF_LIFESKILL_INPUTCOLLECTIONBUTTON		5576 //수집목록에 넣기
#define _XDEF_LIFESKILL_INPUTCOLLECTION_OK			5577 //수집목록에 넣기 수락 
#define _XDEF_LIFESKILL_INPUTCOLLECTION_NO			5578 //수집목록에 넣기 거절
#define _XDEF_LIFESKILL_COLLECTIONEXPLAIN			5579
#define _XDEF_LIFESKILL_EVENTBUTTON					5580 //이벤트 버튼
#define _XDEF_LIFESKILL_TYPEBUTTON7					5581


#define _XDEF_WTITLE_LOGINSERVERLIST				10203 //_T("Login")

#define _XDEF_WTITLE_TRAININGCOMPLETE				10204

#define _XDEF_WTITLE_TESTSERVERNOTICEWINDOW			10205

#define _XDEF_WTITLE_GAMBLE							10206	// "gamble" 2004.11.3->hotblood insert
#define _XDEF_GAMBLE_OPEN							5601
#define _XDEF_GAMBLE_CANCLE							5602
#define _XDEF_GAMBLE_HELP							5603
#define _XDEF_GAMBLE_CLOSE							5604
#define _XDEF_GAMBLE_STOPOK							5605
#define _XDEF_GAMBLE_STOPNO							5606
#define _XDEF_GAMBLE_OPENOK							5607
#define _XDEF_GAMBLE_OPENNO							5608

#define _XDEF_WTITLE_EVENTNOTICEWINDOW				10207	// "EventNotice" 
#define _XDEF_EVENTNOTICE_CLOSE						5620
#define _XDEF_EVENTNOTICE_CHECK						5621

#define _XDEF_WTITLE_TARGETINFOWINDOW				10208	// "TargetInfo" 
#define _XDEF_TARGETINFOWINDOW_CLOSEBUTTON			5650
#define _XDEF_TARGETINFOWINDOW_HELPBUTTON			5651

#define _XDEF_WTITLE_PVPBROKER						10209	// "비무 중개"
#define _XDEF_MATCH_REGISTRATION					5701	// 비무 등록
#define _XDEF_MATCH_REQUESTPVP						5702	// 개인 비무 신청
#define _XDEF_MATCH_REQUESTPVPGROUP					5703	// 집단 비무 신청
#define _XDEF_MATCH_REQUESTLIST						5704	// 비무 목록 요청

#define _XDEF_PVPBROKER_CLOSE						5705	// 비무 중개 윈도우 닫기
#define _XDEF_PVPBROKER_LISTBOX						5706
#define _XDEF_PVPBROKER_REQUESTPVP					5707	// 비무 중계 윈도우에서 신청

#define _XDEF_MATCH_REQUESTFROMOTHER_OK				5708	// 다른 사람으로부터의 신청 - OK
#define _XDEF_MATCH_REQUESTFROMOTHER_NO				5709	// 다른 사람으로부터의 신청 - NO
#define _XDEF_MATCH_WAITEXIT						5710	// 비무장에서 나가기 요청
#define _XDEF_MATCH_REGISTCANCEL					5711	// 비무 목록에서 해지요청

#define _XDEF_WTITLE_MATCHTABLEPVP					10210	// "개인비무첩"
#define _XDEF_MATCHINFO_TAB							5801
#define _XDEF_MATCHTABLEPVP_TAB						5802
#define _XDEF_MATCHTABLEGROUP_TAB					5803
#define _XDEF_MATCHTABLERACE_TAB					5804

#define _XDEF_MATCHTABLEPVP_CLOSE					5805
#define _XDEF_MATCHTABLEPVP_MONEY					5806
#define _XDEF_MATCHTABLEPVP_CONFIRM					5807
#define _XDEF_MATCHTABLEPVP_CANCEL					5808
#define _XDEF_MATCHTABLEPVP_MATCHCLASSBTN			5809
#define _XDEF_MATCHTABLEPVP_MATCHTYPEBTN			5810
#define _XDEF_MATCHTABLEPVP_MATCHTIMEBTN			5811
#define _XDEF_MATCHTABLEPVP_USEHYPERRUNBTN			5812
#define _XDEF_MATCHTABLEPVP_USEBUFFBTN				5813
#define _XDEF_MATCHTABLEPVP_MATCHBALANCEBTN			5814

#define _XDEF_MATCHTABLEPVP_MATCHCLASSLBOX			5815
#define _XDEF_MATCHTABLEPVP_MATCHTYPELBOX			5816
#define _XDEF_MATCHTABLEPVP_MATCHTIMELBOX			5817
#define _XDEF_MATCHTABLEPVP_USEHYPERRUNLBOX			5818
#define _XDEF_MATCHTABLEPVP_USEBUFFLBOX				5819
#define _XDEF_MATCHTABLEPVP_MATCHBALANCELBOX		5820
#define _XDEF_MATCHTABLEPVP_MATCHBALANCESLIDER		5821

#define _XDEF_WTITLE_SOCKETPLUGINEXP				10211	// "장식물 확장/분리/파괴" 
#define _XDEF_SOCKETPLUGINEXP_START					5850
#define _XDEF_SOCKETPLUGINEXP_CANCLE				5851
#define _XDEF_SOCKETPLUGINEXP_SEPARATION			5852
#define _XDEF_SOCKETPLUGINEXP_DESTROY				5853
#define _XDEF_SOCKETPLUGINEXP_HELP					5854


#define _XDEF_WTITLE_MATCHNOTICELARGE				10212	// 비무전광판
#define _XDEF_MATCHNOTICE_CLOSE						5901
#define _XDEF_MATCHFREE_ENTER						5902	// 자유비무장으로 입장

#define _XDEF_WTITLE_MATCHNOTICESMALL				10213	// 비무 플레이어창

#define _XDEF_WTITLE_MATCHMESSAGE					10214	// 비무 메세지

#define _XDEF_WTITLE_MATCHPR						10215	// 비무홍보입력창
#define _XDEF_MATCHPR_CLOSEBUTTON					5951	
#define _XDEF_MATCHPR_OPENBUTTON					5952	
#define _XDEF_MATCHPR_HELPBUTTON					5953

#define _XDEF_WTITLE_MATCHRECORD					10216	// 비무 전적 창	
#define _XDEF_MATCHRECORD_CLOSE						5981

#define _XDEF_WTITLE_AREASELECTWINDOW_WHITE			10217	// 낭인 통합게이트 통과시 영역 선택 윈도우
#define _XDEF_AREASELECTWINDOW_LISTBOX				6000
#define _XDEF_AREASELECTWINDOW_CLOSEBUTTON			6001    // 취소
#define _XDEF_AREASELECTWINDOW_MOVEBUTTON			6002	// 서버간 이동 버튼

#define _XDEF_WTITLE_AREASELECTWINDOW_BLACK			10218	// 낭인 통합게이트 통과시 영역 선택 윈도우

#define _XDEF_WTITLE_CASHITEM						10219	// 캐쉬 아이템 창
#define _XDEF_CASHITEM_REFRESH_BTN					6030
#define _XDEF_CASHITEM_ALLMOVE_BTN					6031
#define _XDEF_CASHITEM_BUYITEM_BTN					6032
#define _XDEF_CASHITEM_PRESENTITEM_BTN				6033
#define _XDEF_CASHITEM_CLOSE_BTN					6034
#define _XDEF_CASHITEM_HELPE_BTN					6035
#define _XDEF_CASHITEM_ALLMOVEYES_BTN				6036
#define _XDEF_CASHITEM_ALLMOVENO_BTN				6037
#define _XDEF_CASHITEM_QUESIZE						6038

#define _XDEF_WTITLE_NPCCOLLECTION					10220	// NPC 명품 수집 창
#define _XDEF_NPCCOLLECTION_HELP_BTN				6050
#define _XDEF_NPCCOLLECTION_REWARDSET01_BTN			6051
#define _XDEF_NPCCOLLECTION_REWARDSET02_BTN			6052
#define _XDEF_NPCCOLLECTION_REWARDSET03_BTN			6053
#define _XDEF_NPCCOLLECTION_REWARDSET04_BTN			6054
#define _XDEF_NPCCOLLECTION_COLLECTIONLISTBOX		6055
#define _XDEF_NPCCOLLECTION_SELECTREWARD_OK			6056
#define _XDEF_NPCCOLLECTION_SELECTREWARD_NO			6057

#define _XDEF_WTITLE_NPCRESOURCE					10221	// NPC 자원 수집 창
#define _XDEF_NPCRESOURCE_HELP_BTN					6060
#define _XDEF_NPCRESOURCE_EXCHANGE_BTN				6061
#define _XDEF_NPCRESOURCE_RESOURCELISTBOX			6062
#define _XDEF_NPCRESOURCE_EXCHANGE_OK				6063
#define _XDEF_NPCRESOURCE_EXCHANGE_NO				6064

#define _XDEF_WTITLE_INCHANT						10222	// 무기 제련 창
#define _XDEF_INCHANT_STARTBUTTON					6070
#define _XDEF_INCHANT_CANCLEBUTTON					6071
#define _XDEF_INCHANT_HELPBUTTON					6072
#define _XDEF_INCHANT_STARTYESBUTTON				6073
#define _XDEF_INCHANT_STARTNOBUTTON					6074
#define _XDEF_INCHANT_PERIODITEM_YES				6075	// 기간제 아이템 제련
#define _XDEF_INCHANT_PERIODITEM_NO					6076

#define _XDEF_WTITLE_NPCBUFF						10223	// NPC buff창
#define _XDEF_NPCBUFF_CLOSE							6100
#define _XDEF_NPCBUFF_APPLY							6101
#define _XDEF_NPCBUFF_LISTBOX						6102
#define _XDEF_NPCBUFF_APPLY_OK						6103	

#define _XDEF_WTITLE_PAYMENTMETHODWINDOW			10224	// 베트남 SDS용 윈도우

#define _XDEF_WTITLE_BOOKOPENWINDOW					10225	// Book Open Window
#define _XDEF_BOOKOPEN_CLOSE						6130

#define _XDEF_WTITLE_QUESTRANKWINDOW				10226	// Quest Ranking Window
#define _XDEF_QUESTRANK_HELP_BTN					6140
#define _XDEF_QUESTRANK_LISTBOX						6141

#define _XDEF_WTITLE_GUIDELINEWINDOW				10227	// "GuideLine Window

#define _XDEF_WTITLE_PKWINDOW						10228 // "PK Window"

#define _XDEF_WTITLE_BLOODPOINTWINDOW				10229 // "Blood point window"
#define _XDEF_BLOODPOINT_REQITEM					6160 

#define _XDEF_WTITLE_PKRECORD						10230 // "PK Record Window"
#define _XDEF_PKRECORD_TAB_1						6170
#define _XDEF_PKRECORD_TAB_2						6171
#define _XDEF_PKRECORD_TAB_3						6172
#define _XDEF_PKRECORD_TAB_4						6173
#define _XDEF_PKRECORD_TAB_5						6174

#define _XDEF_WTITLE_SERVERUNIFICATIONWINDOW		10231	// "ServerUnification Window
#define _XDEF_SU_NEXTBUTTON							6190
#define _XDEF_SU_PREVBUTTON							6191
#define _XDEF_SU_EXITBUTTON							6192
#define _XDEF_SU_CHECKBTN1							6193
#define _XDEF_SU_CHECKBTN2							6194
#define _XDEF_SU_CHECKBTN3							6195
#define _XDEF_SU_CHECKBTN4							6196
#define _XDEF_SU_CHECKBTN5							6197
#define _XDEF_SU_CHECKBTN6							6198
#define _XDEF_SU_CHECKBTN7							6199
#define _XDEF_SU_CHECKBTN8							6200
#define _XDEF_SU_CHECKBTN9							6201
#define _XDEF_SU_CHECKBTN10							6202
#define _XDEF_SU_CHECKBTN11							6203
#define _XDEF_SU_CHECKBTN12							6204
#define _XDEF_SU_CHANGEBTN1							6205
#define _XDEF_SU_CHANGEBTN2							6206
#define _XDEF_SU_CHANGEBTN3							6207
#define _XDEF_SU_NOTSELECT_WAREHOUSE				6208
#define _XDEF_SU_NOTSELECT_CHARACTER				6209
#define _XDEF_SU_INPUT_JUMINNUMBER					6210
#define _XDEF_SU_UNIFICATION_YES					6211


#define _XDEF_WTITLE_DRAWKEYBOARDWINDOW				10232	// "DrawKeyboard Window"

#define _XDEF_WTITLE_CHANGENAMEWINDOW				10233	// "ChangeName Window"
#define _XDEF_CN_CHANGENAMEYES						6220
#define _XDEF_CN_CHANGENAMENO						6221
#define _XDEF_CN_CHANGENAMEREALYES					6222

#define _XDEF_WTITLE_HELPSCREENWINDOW				10234	// "HelpScreen Window"

#define _XDEF_WTITLE_AREASELECTWINDOW_MULTI			10235	// 다중 통합게이트 통과시 영역 선택 윈도우

#define _XDEF_WTITLE_NPCSEARCHWINDOW				10236	// NPCSearch Window
#define _XDEF_NPCSEARCH_CLOSE						6250
#define _XDEF_NPCSEARCH_LISTBOX						6251

#define _XDEF_WTITLE_CASHMALL						10237	// Cash Mall Window
#define _XDEF_CASHMALL_BTN_CLOSE					6260

#define _XDEF_WTITLE_CASHBOX						10238	// Cash Box Window
#define _XDEF_CASHBOX_BTN_CLOSE						6270
#define _XDEF_CASHBOX_BTN_RENEW						6271
#define _XDEF_CASHBOX_BTN_MOVE						6272
#define _XDEF_CASHBOX_BTN_ALLMOVE					6273
#define _XDEF_CASHBOX_BTN_MOVECASHMALL				6274
#define _XDEF_CASHBOX_LISTBOX_CASHITEM				6275
#define _XDEF_CASHBOX_TABBUTTON_PERSONAL			6276
#define _XDEF_CASHBOX_TABBUTTON_PRESENT				6277
#define _XDEF_CASHBOX_BTN_FIRST						6278
#define _XDEF_CASHBOX_BTN_END						6279
#define _XDEF_CASHBOX_BTN_ADJACENT					6280
#define _XDEF_CASHBOX_BTN_NEXT						6281
#define _XDEF_CASHBOX_BTN_PAGE1						6282
#define _XDEF_CASHBOX_BTN_PAGE2						6283
#define _XDEF_CASHBOX_BTN_PAGE3						6284
#define _XDEF_CASHBOX_BTN_PAGE4						6285
#define _XDEF_CASHBOX_BTN_PAGE5						6286
#define _XDEF_CASHBOX_BTN_MSG1						6287
#define _XDEF_CASHBOX_BTN_MSG2						6288
#define _XDEF_CASHBOX_BTN_MSG3						6289
#define _XDEF_CASHBOX_BTN_MSG4						6290
#define _XDEF_CASHBOX_BTN_MSG5						6291
#define _XDEF_CASHBOX_BTN_MSG6						6292
#define _XDEF_CASHBOX_BTN_MSG7						6293
#define _XDEF_CASHBOX_BTN_MSG8						6294
#define _XDEF_CASHBOX_BTN_MSG9						6295
#define _XDEF_CASHBOX_BTN_MSG9						6295
#define _XDEF_CASHBOX_BTN_MSGCLOSE					6296

// Cash Item 관련
#define _XDEF_CASHITEMUSE_SHOUTYES					6300	// 외치기 사용 OK
#define _XDEF_CASHITEMUSE_SHOUTNO					6301	// 외치기 사용 NO
#define _XDEF_CASHITEMUSE_RESETPOINTYES				6302	// 오기/오의 초기화 사용 OK
#define _XDEF_CASHITEMUSE_RESETPOINTNO				6303	// 오기/오의 초기화 사용 NO
#define _XDEF_CASHITEMUSE_ADDEXPYES					6304	// 경험치/숙련도 증가 사용 OK
#define _XDEF_CASHITEMUSE_ADDEXPNO					6305	// 경험치/숙련도 증가 사용 NO
#define _XDEF_CASHITEMUSE_CLEARNICKNAMEYES			6306	// 별호 변경시간 초기화 YES
#define _XDEF_CASHITEMUSE_CLEARNICKNAMENO			6307	// 별호 변경시간 초기화 NO

#define _XDEF_WTITLE_ACCOUNTITEMUSE					10239	// 경험치/숙련도/구룡기행 window

#define _XDEF_WTITLE_MOVEVILLAGE					10240	// 표국 이동 window
#define _XDEF_MOVEVILLAGE_MOVEBUTTON				6400	// 이동 버튼
#define _XDEF_MOVEVILLAGE_LISTBOX					6401
#define _XDEF_MOVEVILLAGE_DECIDEMOVING				6402
#define _XDEF_MOVEVILLAGE_CANCEL					6403

#define _XDEF_WTITLE_EVENT							10241	// "Event Window" 이벤트 입력 윈도우
#define _XDEF_EVENT_BTN_CLOSE						6450	// 닫기 버튼
#define _XDEF_EVENT_BTN_HELP						6451	// 도움 버튼
#define _XDEF_EVENT_LISTBOX_TITLE					6452	// 이벤트 목록
#define _XDEF_EVENT_LISTBOX_DESCRIPTION				6453	// 이벤트 설명 
#define _XDEF_EVENT_BTN_OK							6454	// 이벤트 시리얼 번호 입력완료 버튼  
#define _XDEF_EVENT_BTN_GET							6455    // 아이템 받기 버튼
#define _XDEF_EVENT_BTN_APPLY						6456    // 아이템 요청


#define _XDEF_WTITLE_EXPLAINCHARACTER				10242	// 캐릭터 생성창에서 자세한 설명을 보여주는 창
#define _XDEF_EXPLAINCHARACTER_BTN_01				6500	// 버튼1
#define _XDEF_EXPLAINCHARACTER_BTN_02				6501	// 버튼2
#define _XDEF_EXPLAINCHARACTER_BTN_03				6502	// 버튼3
#define _XDEF_EXPLAINCHARACTER_BTN_04				6503	// 버튼4
#define _XDEF_EXPLAINCHARACTER_BTN_05				6504	// 버튼5
#define _XDEF_EXPLAINCHARACTER_BTN_06				6505	// 버튼6
#define _XDEF_EXPLAINCHARACTER_BTN_07				6506	// 버튼7
#define _XDEF_EXPLAINCHARACTER_BTN_08				6507	// 버튼8
#define _XDEF_EXPLAINCHARACTER_BTN_09				6508	// 버튼9
#define _XDEF_EXPLAINCHARACTER_BTN_10				6509	// 버튼10
#define _XDEF_EXPLAINCHARACTER_BTN_11				6510	// 버튼11
#define _XDEF_EXPLAINCHARACTER_BTN_12				6511	// 버튼12


#define _XDEF_WTITLE_WEBBOARD						10243	// Web Board Window
#define _XDEF_WEBBOARD_BTN_CLOSE					6550

#define _XDEF_WTITLE_CASTLEINFO						10244	// castleinfo window
#define _XDEF_CASTLEINFO_REQWAR						6600	// 도전 예약
#define _XDEF_CASTLEINFO_REQWAR_YES					6601	// 도전 예약
#define _XDEF_CASTLEINFO_CANCELWAR					6602	// 도전 취소

#define _XDEF_WTITLE_CHALLENGERLIST					10245	// challenger list window
#define _XDEF_CHALLENGERLIST_REQLIST				6650	// 목록 보기
#define _XDEF_CHALLENGERLIST_LISTBOX				6651	// 도전자 목록 listbox 

#define _XDEF_WTITLE_CASTLEBATTLE_SHOUT				10246	//장원전 사자후 윈도우 ID
#define _XDEF_CASTLEBATTLE_SHOUT_BTN_CLOSE			6700	//장원전 사자후 닫기 버튼 ID
#define _XDEF_CASTLEBATTLE_SHOUT_BTN_SHOUT			6701	// 장원전 사자후 외치기 버튼 ID

#define _XDEF_WTITLE_CASTLEBATTLE_TIMECHANGE		10247	//장원전 시간변경 윈도우 ID
#define _XDEF_CASTLEBATTLE_TIMECHANGE_BTN_CLOSE		6750	//장원전 시간변경 닫기, 취소 버튼 ID
#define _XDEF_CASTLEBATTLE_TIMECHANGE_BTN_CHANGE	6751	// 장원전 시간변경 변경 버튼 ID
#define _XDEF_CASTLEBATTLE_TIMECHANGE_BTN_LISTDOWN1	6752	// 장원전 시간변경 리스트1 버튼 ID
#define _XDEF_CASTLEBATTLE_TIMECHANGE_BTN_LISTDOWN2	6753	// 장원전 시간변경 리스트2 버튼 ID
#define _XDEF_CASTLEBATTLE_TIMECHANGE_BTN_LISTDOWN3	6754	// 장원전 시간변경 리스트3 버튼 ID
#define _XDEF_CASTLEBATTLE_TIMECHANGE_LISTBOX_TIME1	6755	// 장원전 시간변경 리스트박스
#define _XDEF_CASTLEBATTLE_TIMECHANGE_LISTBOX_TIME2	6756	// 장원전 시간변경 리스트박스
#define _XDEF_CASTLEBATTLE_TIMECHANGE_LISTBOX_TIME3	6757	// 장원전 시간변경 리스트박스

#define _XDEF_WTITLE_CBRESULTNOTICE					10248	// 장원전 결과 알림 윈도우
#define _XDEF_CBRESULTNOTICE_CLOSE					6780	// 창 닫기

#define _XDEF_WTITLE_CASTLEBATTLE_REWARDLIST  		10249	//장원전 포상내역 윈도우 ID
#define _XDEF_CASTLEBATTLE_REWARDLIST_BTN_OK		6800	//장원전 포상내역 확인 버튼 ID

#define _XDEF_WTITLE_CASTLEBATTLE_PERSONALHISTORY 	10250	//장원전 시간확인 : 장원혈 윈도우 ID
#define _XDEF_CASTLEBATTLE_PERSONALHISTORY_BTN_CLOSE 6850	//장원전 시간확인 : 장원혈 닫기 버튼 ID
#define _XDEF_CASTLEBATTLE_PERSONALHISTORY_CHANGE	6851	//장원전 시간확인 : 장원혈 리사이즈 버튼 ID
#define _XDEF_CBPERSONAL_VIEWRECORD					6852	//전적보기 버튼

#define _XDEF_WTITLE_ESCAPE							10251	//탈출 윈도우 ID
#define _XDEF_ESCAPE_BTN_CANCLE						6900	//탈출 취소 버튼 ID

#define _XDEF_WTITLE_THREATENGAUGE					10252	// 장원전 - 협박 진행 gauge 
#define _XDEF_WTITLE_MARK							10253	// 장원전 - 피아식별 마크

#define _XDEF_WTITLE_PKTRACINGREQUEST				10254	//PK추적의뢰 윈도우 ID
#define _XDEF_PKTRACINGREQUEST_BTN_CANCLE			7050	//PK추적의뢰 취소 버튼 ID
#define _XDEF_PKTRACINGREQUEST_BTN_REQUEST1			7051	//PK추적의뢰1 버튼 ID
#define _XDEF_PKTRACINGREQUEST_BTN_REQUEST2			7052	//PK추적의뢰2 버튼 ID
#define _XDEF_PKTRACINGREQUEST_BTN_REQUEST3			7053	//PK추적의뢰3 버튼 ID
#define _XDEF_PKTRACINGREQUEST_BTN_REQUESTCANCE		7054	//메세지 박스 취소
#define _XDEF_PKTRACINGREQUEST_BTN_REQUEST1_YES		7055	//PK추적의뢰1 버튼 ID
#define _XDEF_PKTRACINGREQUEST_BTN_REQUEST2_YES		7056	//PK추적의뢰2 버튼 ID
#define _XDEF_PKTRACINGREQUEST_BTN_REQUEST3_YES		7057	//PK추적의뢰3 버튼 ID

#define _XDEF_WTITLE_PK_TRACINGSERVICES				10255	//PK 위치추적  윈도우 ID
#define _XDEF_PK_TRACINGSERVICES_BTN_CLOSE			7100	//PK 위치추적 닫기 버튼 ID
#define _XDEF_PK_TRACINGSERVICES_LISTBOX			7101	//PK 위치추적 리스트 박스

#define _XDEF_WTITLE_CBRECORD						10256	// 장원전 중 개인전적
#define _XDEF_CBRECORD_LISTBOX						7130	

#define _XDEF_WTITLE_SMELT_ITEM_WINDOW				10277	//용루, 용린창
#define _XDEF_SMELT_CONFIRMBUTTON					7150	//확인
#define _XDEF_SMELT_CANCLEBUTTON					7151	//취소
#define _XDEF_SMELT_CLOSEBUTTON						7152	//닫기
#define _XDEF_SMELT_PERIODITEM_YES					7153	// 기간제 아이템에 사용
#define _XDEF_SMELT_PERIODITEM_NO					7154

#define _XDEF_WTITLE_CBORGRECORD					10278	// 장원전 후 전체 전적
#define _XDEF_CBORGRECORD_OK						7200	// 확인

#define _XDEF_WTITLE_CBREWARDSMALL					10279	// 장원전 보상 -  개인보상
#define _XDEF_CBREWARDSMALL_OK						7210	// 확인

#define _XDEF_WTITLE_BLACKLISTWINDOW				10280 //_T("Messenger")
#define _XDEF_BLACKLISTWINDOW_CLOSEBUTTON			7230 
#define _XDEF_BLACKLISTWINDOW_HELPBUTTON			7231 
#define _XDEF_MESSENGERWINDOW_ADDBLACKLISTBUTTON	7232
#define _XDEF_MESSENGERWINDOW_DELETEBLACKLISTBUTTON	7233 
#define _XDEF_MESSENGERWINDOW_BLACKLISTBOX		 	7234 
#define _XDEF_MESSENGERWINDOW_ADD_MESSAGEBOX		7235 
#define _XDEF_MESSENGERWINDOW_DELETE_MESSAGEBOX		7236 

#define _XDEF_WTITLE_WORLDMAP						10281 // Author : 양희왕 // breif : 신구룡전도
#define	_XDEF_WORLDMAP_STARTBUTTON					7250
#define _XDEF_WORLDMAP_CLOSEBUTTON					7251  // 닫기
#define _XDEF_WORLDMAP_MAPBUTTON_01					7252  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_02					7253  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_03					7254  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_04					7255  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_05					7256  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_06					7257  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_07					7258  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_08					7259  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_09					7260  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_10					7261  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_11					7262  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_12					7263  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_13					7264  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_14					7265  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_15					7266  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_16					7267  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_17					7268  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_18					7269  // 맵 버튼
#define _XDEF_WORLDMAP_MAPBUTTON_19					7270  // 맵 버튼

#define _XDEF_WTITLE_AGEGRADE_WINDOW				10282 //Author :양희왕 //breif : 이용등급

#define _XDEF_WTITLE_RECALLITEM_WINDOW				10283 //Author : 양희왕 //breif : 친구소환
#define _XDEF_RECALLITEM_CALLBUTTON					7300  //호출 버튼
#define _XDEF_RECALLITEM_MOVEBUTTON					7301  //이동 버튼
#define _XDEF_RECALLITEM_CLOSEBUTTON				7302  //닫기 버튼
#define _XDEF_RECALLITEM_LISTBOX					7304  //친구 리스트박스 
#define _XDEF_RECALLITEM_MINICLOSEBUTTON			7305  //작은 닫기
#define _XDEF_RECALLITEM_CALLBUTTON_YES				7306  //호출 확인
#define _XDEF_RECALLITEM_CALL_AGREE					7307  //호출 요구 수락
#define _XDEF_RECALLITEM_CALL_REJECT				7308  //호출 요구 거절
#define _XDEF_RECALLITEM_MOVEBUTTON_YES				7309  //이동 확인
#define _XDEF_RECALLITEM_MOVE_AGREE					7310  //이동 요구 수락
#define _XDEF_RECALLITEM_MOVE_REJECT				7311  //이동 요구 거절

#define _XDEF_WTITLE_SOCKETDETACH_WINDOW			10284 //Author : 양희왕 //breif : 소켓제거
#define	_XDEF_SOCKETDETACH_PROCESSBUTTON			7350 // 물품내리기, 장식물 분리
#define	_XDEF_SOCKETDETACH_YESBUTTON				7351 // 장착물 분리 확인
#define _XDEF_SOCKETDETACH_CANCEL					7352 //취소 버튼
#define _XDEF_SOCKETDETACH_CLOSE					7353 //닫기
#define _XDEF_SOCKETDETACH_HELP						7354 //도움

#define _XDEF_WTITLE_PCRPREMIUN_WINDOW				10285 // PC방 표시 window

#define _XDEF_WTITLE_POISON_WINDOW					10286 // 중독 표시 window

#define _XDEF_WTITLE_EXP_WINDOW						10287 // 경험치 window
#define _XDEF_EXPWINDOW_CONVERGENCE					7400  // 폭주 (interface renewal)

#define _XDEF_WTITLE_MIXWEAPON_WINDOW				10288 // 무기 조합 window
#define _XDEF_MIXWEAPON_OK							7450  // 확인
#define _XDEF_MIXWEAPON_CANCEL						7451  // 취소

#define _XDEF_WTITLE_MATCHEVENT						10289 // 비무 대회 (자유비무)window

#define _XDEF_WTITLE_REWARDNICK						10290 // 비무대회 우승 별호

#define _XDEF_WTITLE_INFOWINDOW						10291 // 장원전 정보(버프형) 창 

#define _XDEF_WTITLE_FREEMATCHINFO					10292 // 비무 대회 정보
#define _XDEF_FMINFO_CLOSE							7500  // 확인

#define _XDEF_WTITLE_EVENT_RENEWAL_WINDOW			10293 // Author : 양희왕 //breif : 이벤트 아이콘

#define _XDEF_WTITLE_NEW_RESOURCEWINDOW				10294 // NEW 재료 수집 창
#define _XDEF_NEWRESOURCEWINDOW_RESOURCELIST		7550
#define _XDEF_NEWRESOURCEWINDOW_EXCHANGE			7551
#define _XDEF_NEWRESOURCEWINDOW_CLOSE				7552
#define _XDEF_NEWRESOURCEWINDOW_EXCHANGE_OK			7553
#define _XDEF_NEWRESOURCEWINDOW_EXCHANGE_NO			7554

#define _XDEF_WTITLE_TARGETINFOSELECTWINNDOW		10295 // Author : 양희왕 //breif : 상대정보 선택하는 창

#define _XDEF_WTITLE_NPCMNDWINDOW					10296 //Author : 양희왕 //breif : NPC 사제 창
#define _XDEF_WTITLE_NPCMNDAPPLYBUTTON				7600 //사제 신청 버튼	
#define _XDEF_WTITLE_NPCMNDREQLISTBTN				7601 //리스트 요청 버튼

#define _XDEF_WTITLE_MNDCURRENTPOINTWINDOW			10297  //Author : 양희왕 //breif : 사제 현재 죽인 몬스터 카운트

#define _XDEF_WTITLE_MNDTOTALPOINTWINDOW			10298  //Author : 양희왕 //breif : 사제 토탈 죽인 몬스터 카운트

#define _XDEF_WTITLE_MESSAGEWINDOW					30000 // "Message window"
#define _XDEF_WTITLE_BOSSMESSAGEWINDOW				30001 // "Message window"
#define _XDEF_WTITLE_NPCTRADEMESSAGEWINDOW			30002 		
#define _XDEF_WTITLE_GAMEEXITMESSAGEWINDOW			30003
#define _XDEF_WTITLE_PCTRADEMESSAGEWINDOW			30004
#define _XDEF_WTITLE_SOCKETPLUGINMESSAGEWINDOW		30005 // "Message window"
#define _XDEF_WTITLE_TARGETINFONMESSAGEWINDOW		30006 // "TargetInfo window"
#define _XDEF_WTITLE_EVENTMESSAGEWINDOW				30007 // "Event window"
#define _XDEF_WTITLE_HEALMESSAGEWINDOW				30008 // "Heal window"
#define _XDEF_WTITLE_BILLINGTIMOUTMESSAGEWINDOW		30009 // "Billing timeout"
#define _XDEF_WTITLE_INCHANTMESSAGEWINDOW			30010 // "Inchant Window"
#define _XDEF_WTITLE_STATECANCLEMESSAGEWINDOW		30011 // "State Window"
#define _XDEF_WTITLE_DELETESKILLMESSAGEWINDOW		30012 // "Delete Skill"
#define _XDEF_WTITLE_ENTERBOSSROOMUSECASHITEMWINDOW	30013



#define _XDEF_LOADINGBTN_WATCHANDWINBUTTON			6700  // Acclaim watch and win advertise button


// "Tutorial window" [ 40000~40100까지 사용 ]


//////////////////////////////////////////////////////////////////////////
// "Messenger Dialog Window" [60000 ~ 60050 까지 사용]
//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////
// "Quest Mail Window" [60051 ~ 60056 까지 사용]
//////////////////////////////////////////////////////////////////////////

#define _XDEF_RENDERTEXTURERANGE	3.0f
#define _XDEF_SHADOWOBJECTRANGE		2.0f

#define _XDEF_MESSAGEDIALOGDLGPOS_WIDTH		326
#define _XDEF_MESSAGEDIALOGDLGPOS_HEIGHT	68

#endif //end of _XPROC_PROCESSDEFINE
