////////////////////////////////////////////////////////////
//
//  GEN_DEFS.H - General Definitions and Data Types Include
//               File
//
//  Version:    1.00B
//
//  History:    94/08/23 - Version 1.00A release.
//              94/11/11 - Version 1.00B release.
//
//  Compilers:  Microsoft Visual C/C++ Professional V1.5
//              Borland C++ Version 4.0
//
//  Author:     Ian Ashdown, P.Eng.
//              byHeart Software Limited
//              620 Ballantree Road
//              West Vancouver, B.C.
//              Canada V7S 1W3
//              Tel. (604) 922-6148
//              Fax. (604) 987-7621
//
//  Copyright 1994 byHeart Software Limited
//
////////////////////////////////////////////////////////////

#ifndef _GEN_DEFS_H
#define _GEN_DEFS_H

#define FALSE   0
#define TRUE    1

typedef int BOOL;
typedef long LONG;
typedef unsigned char BYTE;
typedef unsigned int UINT;
typedef unsigned long DWORD;
typedef unsigned short WORD;

#endif

