#ifndef __SOUNDEFFECT_H__
#define __SOUNDEFFECT_H__

extern int				ID_SR_INTERFACE_DROP_METAL_003_WAV;
extern int				ID_SR_INTERFACE_DROP_METAL_002_WAV;
extern int				ID_SR_INTERFACE_DROP_METAL_001_WAV;
extern int				ID_SR_INTERFACE_DROP_LIGHT_001_WAV;
extern int				ID_SR_INTERFACE_DROP_HOOP_001_WAV;
extern int				ID_SR_INTERFACE_DROP_GLASS_DROP_001_WAV;
extern int				ID_SR_INTERFACE_DROP_CLOTH_001_WAV;
extern int				ID_SR_INTERFACE_DROP_CHOP_002_WAV;
extern int				ID_SR_INTERFACE_DROP_CHOP_001_WAV;
extern int				ID_SR_INTERFACE_COOLDOWN_WAV;
extern int				ID_SR_INTERFACE_CLOTHESDROP01_WAV;
extern int				ID_SR_INTERFACE_CHOICEICON01_WAV;
extern int				ID_SR_INTERFACE_CHARACTER_START_WAV;
extern int				ID_SR_INTERFACE_BURNANGER01_WAV;
extern int				ID_SR_INTERFACE_BIGBUTTONCLICK01_WAV;
extern int				ID_SR_INTERFACE_ANGERFIRE01_WAV;
extern int				ID_SR_INTERFACE_WOODDROP01_WAV;
extern int				ID_SR_INTERFACE_WINDOWOPEN01_WAV;
extern int				ID_SR_INTERFACE_WINDOWCLOSE01_WAV;
extern int				ID_SR_INTERFACE_WARNING01_WAV;
extern int				ID_SR_INTERFACE_USE_FIRE_WAV;
extern int				ID_SR_INTERFACE_USE_EAT_004_WAV;
extern int				ID_SR_INTERFACE_USE_EAT_003_WAV;
extern int				ID_SR_INTERFACE_USE_EAT_002_WAV;
extern int				ID_SR_INTERFACE_USE_EAT_001_WAV;
extern int				ID_SR_INTERFACE_USE_BOOK_001_WAV;
extern int				ID_SR_INTERFACE_TUTO_01_WAV;
extern int				ID_SR_INTERFACE_TARGETING00_WAV;
extern int				ID_SR_INTERFACE_STARTGAME_WAV;
extern int				ID_SR_INTERFACE_SMALLBUTTONCLICK_WAV;
extern int				ID_SR_INTERFACE_SLIDEBUTTON01_WAV;
extern int				ID_SR_INTERFACE_SKILLBOOKDROP01_WAV;
extern int				ID_SR_INTERFACE_SKILL_DOWN_WAV;
extern int				ID_SR_INTERFACE_SKILL_CLICK_WAV;
extern int				ID_SR_INTERFACE_REBORN_WAV;
extern int				ID_SR_INTERFACE_REBIRTH01_WAV;
extern int				ID_SR_INTERFACE_QUICKBUTTONCLICK01_WAV;
extern int				ID_SR_INTERFACE_QUESTSUCCESS01_WAV;
extern int				ID_SR_INTERFACE_QUESTFIND01_WAV;
extern int				ID_SR_INTERFACE_QUESTFAIL01_WAV;
extern int				ID_SR_INTERFACE_PICK_ITEM_001_WAV;
extern int				ID_SR_INTERFACE_NORMALSTART01_WAV;
extern int				ID_SR_INTERFACE_MONEY_01_WAV;
extern int				ID_SR_INTERFACE_LEVELUP01_WAV;
extern int				ID_SR_INTERFACE_LEVELUP_INTRO_WAV;
extern int				ID_SR_INTERFACE_LEVELFAIL_WAV;
extern int				ID_SR_INTERFACE_LEARNSKILL01_WAV;
extern int				ID_SR_INTERFACE_ERROR01_WAV;
extern int				ID_SR_INTERFACE_DROPICON01_WAV;
extern int				ID_SR_INTERFACE_DROP_WOOD_002_WAV;
extern int				ID_SR_INTERFACE_DROP_WOOD_001_WAV;
extern int				ID_SR_INTERFACE_DROP_WHEEP_001_WAV;
extern int				ID_SR_INTERFACE_DROP_SHINE_001_WAV;
extern int				ID_SR_INTERFACE_DROP_PAPER_001_WAV;

extern int				ID_SR_INTERFACE_TRA_COMBO01_WAV;
extern int				ID_SR_INTERFACE_MISS_01_WAV;
extern int				ID_SR_INTERFACE_KIPOINT_01_WAV;
extern int				ID_SR_INTERFACE_BUTTON_WAV;
extern int				ID_SR_INTERFACE_BLUE_01_WAV;
extern int				ID_SR_INTERFACE_WHITE_01_WAV;
extern int				ID_SR_INTERFACE_BLACK_01_WAV;
extern int				ID_SR_INTERFACE_TRA_UP01_WAV;
extern int				ID_SR_INTERFACE_TRA_OK01_WAV;
extern int				ID_SR_INTERFACE_TRA_MISS01_WAV;
extern int				ID_SR_INTERFACE_QUICK_USE_WAV;

extern int				ID_SR_INTERFACE_BOSSBUTTON00_WAV;
extern int				ID_SR_INTERFACE_BOSSBUTTON01_WAV;
extern int				ID_SR_INTERFACE_EARTHQUAKE_WAV;
extern int				ID_SR_INTERFACE_EARTHQUAKE01_WAV;
extern int				ID_SR_INTERFACE_USE_ELIXIR01_WAV;
extern int				ID_SR_INTERFACE_ELIXIR_RUN_WAV;
extern int				ID_SR_INTERFACE_ELIXIR_YES_WAV;
extern int				ID_SR_INTERFACE_ELIXIR_NO_WAV;
extern int				ID_SR_INTERFACE_OPEN_BOX_WAV;

extern int				ID_SR_INTERFACE_INCHANT_01_WAV;
extern int				ID_SR_INTERFACE_INCHANT_02_WAV;
extern int				ID_SR_INTERFACE_INCHANT_03_WAV;
extern int				ID_SR_INTERFACE_MASK_ON;
extern int				ID_SR_INTERFACE_MASK_OFF;
extern int				ID_SR_INTERFACE_CHRISTMAS_WAV;

#ifdef _XDEF_RECALLSYSTEM_070604_MAGVIPER
extern int				ID_SR_INTERFACE_RECALL_WAV;
extern int				ID_SR_INTERFACE_RECALLEFFECT_WAV;
#endif

// 3D sound
extern int				ID_SR_INTERFACE_TURN_POINT00_WAV;

extern int				g_PVPBattleBGMStartIndex;
extern int				g_PVPBattleBGMEndIndex;
extern int				g_PVPBattleFireworkSoundIndex;

extern int				g_BloodInSoundIndex;
extern int				g_BloodOutSoundIndex;

#endif //#ifndef _SOUNDEFFECT_H_

